"""Dashboard data layer: every number shown by the dashboard comes from a function in this module.

Pure functions (no Streamlit) over committed, machine-readable artifacts: configs/*.json,
reports/generated/m3_*/m4_*/m5_*/m6_* and reports/figures/m5/*.png. The frozen model is optional and is loaded only
for the prediction demo, after its SHA-256 is checked against configs/m4_frozen.json. Nothing is trained, re-tuned,
re-thresholded or relabelled here.
"""
import json
import sys
from functools import lru_cache
from pathlib import Path

import numpy as np
import pandas as pd

ROOT = Path(__file__).resolve().parents[1]
if str(ROOT / "src") not in sys.path:  # ids.* helpers (metrics, SHAP) live in src/
    sys.path.insert(0, str(ROOT / "src"))
GEN = ROOT / "reports" / "generated"
FIG = ROOT / "reports" / "figures" / "m5"
NA = "not available"
SHAP_TOL = 1e-9  # live vs stored SHAP agreement required by the case explorer
from ids.metrics import UNSTABLE_SUPPORT as SMALL_SUPPORT  # noqa: E402  (labels below this are case-level only)
FIGURES = {  # Milestone 5 figures reused as-is (generated by scripts/m5_analyze.py)
    "beeswarm": "beeswarm_uniform.png", "dependence": "dependence.png", "family_groups": "family_group_share.png",
    "stability": "stability_bootstrap_ranks.png", "model_comparison": "model_comparison_importance.png",
    "fp_features": "fp_features_by_daygroup.png", "fpr_direction": "fpr_by_direction_val_test.png",
    "score_tails": "benign_score_tails_val_test.png",
}
FAMILY_NAMES = {"lr": "Logistic Regression", "rf": "Random Forest", "lgbm": "LightGBM"}
PROTOCOL_NAMES = {"E1_primary": "chronological (primary)", "E2_random": "random split (comparison)"}


# ------------------------------------------------------------------ raw access
@lru_cache(maxsize=None)
def read_json(rel):
    return json.loads((ROOT / rel).read_text())


@lru_cache(maxsize=None)
def read_csv(name):
    """reports/generated/<name>.csv; round-trip float parsing so stored scores compare exactly (callers must not mutate)."""
    return pd.read_csv(GEN / f"{name}.csv", float_precision="round_trip")


def frozen():
    return read_json("configs/m4_frozen.json")


def protocol():
    return read_json("configs/experiment_protocol_v1.json")


def facts():
    return read_json("reports/generated/m5_facts.json")


def figure(key):
    """Path of a Milestone 5 figure, or None if the file is missing."""
    p = FIG / FIGURES[key]
    return p if p.exists() else None


# ------------------------------------------------------------------ frozen experiment
def budgets():
    """Pre-declared FPR budgets as strings, strictest first (the strictest is the primary operating point)."""
    return sorted(frozen()["experiments"][0]["thresholds"], key=float)


def primary_budget():
    return budgets()[0]


def tag(e):
    return f"{e['experiment']}__{e['family']}"


def experiment(tag_):
    return next(e for e in frozen()["experiments"] if tag(e) == tag_)


def selected():
    fz = frozen()
    return next(e for e in fz["experiments"] if e["run_id"] == fz["overall_selected"])


def summary_row(tag_, subset="full_test", budget=None):
    s = read_csv("m4_test_summary")
    b = float(budget or primary_budget())
    r = s[(s.experiment == tag_) & (s.subset == subset) & np.isclose(s.budget, b)]
    if len(r) != 1:
        raise KeyError(f"no unique summary row for {tag_}/{subset}/{b}")
    return r.iloc[0].to_dict()


def headline():
    """Selected model at the primary budget: frozen threshold, validation and test metrics."""
    e, b = selected(), primary_budget()
    t = summary_row(tag(e), "full_test", b)
    v = e["val_at_threshold"][b]
    return {"run_id": e["run_id"], "tag": tag(e), "family": FAMILY_NAMES[e["family"]], "params": e["params"],
            "best_iteration": e["best_iteration"], "budget": float(b), "threshold": e["thresholds"][b],
            "val_fpr": v["fpr"], "val_recall": v["recall"], "val_fp": v["fp"], "val_fn": v["fn"],
            **{k: t[k] for k in ("n", "attack", "benign", "tp", "fp", "tn", "fn", "precision", "recall", "f1",
                                 "fpr", "pr_auc", "roc_auc")}}


def dataset_overview():
    """Cleaned row count and chronological partition sizes (primary protocol)."""
    c = read_json("reports/generated/m3_cleaning.json")
    p = read_csv("m3_partition_counts")
    p = p[p.protocol == "chrono"].groupby("partition").n.sum()
    return {"dataset": protocol()["source"]["dataset"], "rows_raw": c["rows_in"], "rows_removed": c["rows_removed_non_finite"],
            "rows_clean": c["rows_out"], **{f"n_{k}": int(v) for k, v in p.items()}}


def model_comparison(budget=None):
    """Test metrics of every E1/E2 model at one budget (from the single frozen test evaluation)."""
    rows = []
    for e in frozen()["experiments"]:
        if e["experiment"] not in PROTOCOL_NAMES:
            continue
        r = summary_row(tag(e), "full_test", budget)
        rows.append({"protocol": PROTOCOL_NAMES[e["experiment"]], "model": FAMILY_NAMES[e["family"]],
                     "selected": e["run_id"] == frozen()["overall_selected"],
                     **{k: r[k] for k in ("precision", "recall", "f1", "pr_auc", "roc_auc", "fpr", "fp", "fn")},
                     "val_fpr": e["val_at_threshold"][budget or primary_budget()]["fpr"]})
    return pd.DataFrame(rows)


def confusion(tag_=None, subset="full_test", budget=None):
    r = summary_row(tag_ or tag(selected()), subset, budget)
    return pd.DataFrame([[int(r["tn"]), int(r["fp"])], [int(r["fn"]), int(r["tp"])]],
                        index=["true benign", "true attack"], columns=["predicted benign", "predicted attack"])


def family_recall(tag_=None, subset="full_test", budget=None):
    """Binary-detector recall per original attack label (not multiclass accuracy)."""
    L = read_csv("m4_test_per_label")
    b = float(budget or primary_budget())
    d = L[(L.experiment == (tag_ or tag(selected()))) & (L.subset == subset) & np.isclose(L.budget, b)
          & (L.level == "label_original") & (L.role == "attack")]
    out = d[["label", "n", "flagged", "missed_or_clear", "rate", "ci95_low", "ci95_high"]].rename(
        columns={"flagged": "detected", "missed_or_clear": "missed", "rate": "recall"})
    out["small_support"] = out.n < SMALL_SUPPORT
    out["detected_of_n"] = out.detected.astype(int).astype(str) + "/" + out.n.astype(int).astype(str) + " detected"
    return out.sort_values("n", ascending=False).reset_index(drop=True)


def benign_alerts(tag_=None, budget=None):
    """Alert rate on benign and '- Attempted' labels (all are benign under the protocol-v1 target)."""
    L = read_csv("m4_test_per_label")
    b = float(budget or primary_budget())
    d = L[(L.experiment == (tag_ or tag(selected()))) & (L.subset == "full_test") & np.isclose(L.budget, b)
          & (L.level == "label_original") & (L.role != "attack")]
    return d[["label", "n", "flagged", "rate", "ci95_low", "ci95_high", "unstable"]].sort_values("n", ascending=False)


def small_support_labels():
    fr = family_recall()
    return fr[fr.small_support].sort_values("n")


# ------------------------------------------------------------------ SHAP (Milestone 5)
def shap_global():
    """Global mean |SHAP| ranking (full test census), group shares, and model-agreement / stability summaries."""
    f = facts()
    gp = read_csv("m5_group_share_by_population").set_index("population")
    return {"importance": read_csv("m5_global_importance"), "groups": gp.loc["all_test"].drop("n").sort_values(ascending=False),
            "n_test": f["n_test"], "n_uniform": f["n_uniform"], "base_log_odds": f["base_log_odds"],
            "base_probability": f["base_probability"], "n_inputs": f["n_model_inputs"],
            "additivity_error": f["stored_additivity_max_abs_prob_error"],
            "rf": read_csv("m5_lgbm_vs_rf_summary").set_index("population"),
            "e1e2": read_csv("m5_e1_vs_e2_summary").set_index("population"),
            "boot_top10_min": f["boot1000_top10_overlap_min"], "boot_top1_always": f["boot1000_top1_always"],
            "interaction_share": f["interaction_offdiag_share"], "families": read_csv("m5_family_top_features"),
            "interaction_hub": _hub(read_csv("m5_interactions_top"))}


def _hub(inter):
    """Feature appearing most often among the strongest interaction pairs."""
    return pd.concat([inter.feature_a, inter.feature_b]).value_counts().index[0]


# ------------------------------------------------------------------ false positives (Milestone 5)
def fp_story():
    """Key numbers of the validation->test FPR case study, all from Milestone 4/5 tables."""
    dec = read_csv("m5_shift_decomposition")

    def d(part, dg, rv):
        r = dec[(dec.partition == part) & (dec.daygroup == dg) & (dec.reverse_of_attack == rv)]
        return r.iloc[0].to_dict()
    h, f = headline(), facts()
    cmp_ = read_csv("m5_fp_daygroup_compare").set_index("daygroup")
    prof = read_csv("m5_fp_profile").set_index("daygroup")
    return {"val_fpr": h["val_fpr"], "test_fpr": h["fpr"], "fp": h["fp"], "val_fp": f["val_fp_n"],
            "rev": d("test", "all", True), "other": d("test", "all", False),
            "val_rev": d("val", "all", True), "val_other": d("val", "all", False),
            "by_daygroup": cmp_, "profile": prof, "train_reverse_share": f["train_benign_reverse_share"],
            "E2_fpr_reverse": f["E2_fpr_reverse"], "E2_fp": f["E2_fp"], "fp_n_pairs": f["fp_n_pairs"],
            "fp_top15_pairs_share": f["fp_top15_pairs_share"], "fp_novel": f["fp_novel"]}


def score_hist(set_):
    h = read_csv("m6_score_hist")
    return h[h.set == set_]


# ------------------------------------------------------------------ novel vectors
def novel_overview():
    ns = read_csv("m3_novel_summary")
    r = ns[(ns.protocol == "chrono") & (ns.variant == "primary") & (ns.feature_set == "default")].iloc[0].to_dict()
    rows = []
    for e in frozen()["experiments"]:
        if e["experiment"] != "E1_primary":
            continue
        for sub in ("full_test", "novel_test"):
            s = summary_row(tag(e), sub)
            rows.append({"model": FAMILY_NAMES[e["family"]], "subset": sub, "n": s["n"], "attack": s["attack"],
                         "benign": s["benign"], "recall": s["recall"], "fpr": s["fpr"], "precision": s["precision"],
                         "fp": s["fp"], "fn": s["fn"]})
    return r, pd.DataFrame(rows)


def novel_composition():
    """Attack rows per label in the full test set vs the novel-vector subset (chronological, default features)."""
    d = read_csv("m3_novel_by_label")
    d = d[(d.protocol == "chrono") & (d.variant == "primary") & (d.feature_set == "default") & (d.family != "BENIGN")]
    d = d[["label_original", "full", "novel", "exact_overlap_share"]].rename(columns={"label_original": "label"})
    d["share_of_attacks_full"] = d.full / d.full.sum()
    d["share_of_attacks_novel"] = d.novel / d.novel.sum()
    d["retained"] = d.novel / d.full
    return d.sort_values("full", ascending=False).reset_index(drop=True)


# ------------------------------------------------------------------ prediction demo
def demo_cases_path():
    """Exact benchmark rows for the case explorer: generated locally by scripts/m6_dashboard_data.py, never committed
    (the improved CIC-IDS2017 dataset has no verified redistribution licence)."""
    return ROOT / "artifacts" / "m6" / "demo_cases.csv"


def demo_cases():
    """Local benchmark rows (feature values, stored score and SHAP values), or None in a clone without local data."""
    p = demo_cases_path()
    return pd.read_csv(p, float_precision="round_trip") if p.exists() else None


def casebook():
    """Milestone 5 casebook (committed): stored frozen scores and top SHAP contributions of representative test flows."""
    return read_csv("m5_casebook")


def demo_features():
    return [c[3:] for c in demo_cases().columns if c.startswith("f__")]


def case_contributions(row, k=8):
    """Top-k SHAP contributions (log-odds) toward attack and toward benign for one demo row."""
    s = pd.Series({c[3:]: row[c] for c in row.index if c.startswith("s__")}, dtype=float)
    val = {c[3:]: row[c] for c in row.index if c.startswith("f__")}
    df = pd.DataFrame({"feature": s.index, "shap": s.values, "value": [val[f] for f in s.index]})
    pos = df[df.shap > 0].sort_values("shap", ascending=False, kind="mergesort").head(k)
    neg = df[df.shap < 0].sort_values("shap", kind="mergesort").head(k)
    return pos.reset_index(drop=True), neg.reset_index(drop=True)


def reconstructed_score(row):
    """sigmoid(base + sum SHAP) from the stored SHAP values (base from Milestone 5 facts)."""
    z = facts()["base_log_odds"] + sum(row[c] for c in row.index if c.startswith("s__"))
    return float(1 / (1 + np.exp(-z)))


def model_export():
    """Record of the committed text export of the frozen model (configs/m6_model_export.json)."""
    return read_json("configs/m6_model_export.json")


def model_inputs():
    """Frozen model inputs relative to the manifest's default feature set (from the export record)."""
    inputs = model_export()["input_features"]
    default = read_json("configs/feature_manifest_v1.json")["feature_sets"]["default"]
    return {"n": len(inputs), "n_default": len(default), "has_protocol": "Protocol" in inputs,
            "dropped": [c for c in default if c not in inputs]}


def model_path():
    return ROOT / model_export()["export_path"]


def load_model(path=None, expected_sha=None):
    """Load the committed LightGBM text export of the frozen selected model.

    Accepted only if its SHA-256 matches configs/m6_model_export.json, that record points at the model hash in
    configs/m4_frozen.json, and the booster's input order matches the recorded list.
    Returns (booster or None, status message); never raises for a missing or mismatching file."""
    import hashlib
    rec = model_export()
    path = Path(path or model_path())
    expected_sha = expected_sha or rec["export_sha256"]
    if rec["source_model_sha256"] != selected()["model_sha256"]:
        return None, "model export record does not refer to the frozen model in configs/m4_frozen.json; not loaded"
    if not path.exists():
        return None, f"model export not found: {path.relative_to(ROOT) if path.is_relative_to(ROOT) else path}"
    if hashlib.sha256(path.read_bytes()).hexdigest() != expected_sha:
        return None, "model export present but its SHA-256 does not match configs/m6_model_export.json; not loaded"
    try:
        import lightgbm as lgb
        booster = lgb.Booster(model_file=str(path))
    except Exception as exc:  # corrupt or incompatible file: report, do not crash the page
        return None, f"model export could not be loaded: {exc}"
    if booster.feature_name() != [c.replace(" ", "_") for c in rec["input_features"]]:
        return None, "model export input order differs from configs/m6_model_export.json; not loaded"
    return booster, ("text export of the frozen model loaded; SHA-256 matches configs/m6_model_export.json, which "
                     "records the original model hash from configs/m4_frozen.json")


def live_explain(booster, row):
    """Score one demo row with the frozen-model export and recompute its SHAP values; compare with stored values."""
    feats = model_export()["input_features"]
    x = np.array([[row[f"f__{f}"] for f in feats]], dtype=float)
    score = float(booster.predict(x)[0])
    contrib = booster.predict(x, pred_contrib=True)[0]
    stored = np.array([row[f"s__{f}"] for f in feats], dtype=float)
    return {"score": score, "score_equal_stored": score == float(row["score"]),
            "shap_max_abs_diff": float(np.abs(contrib[:-1] - stored).max()),
            "base_equal_stored": float(contrib[-1]) == facts()["base_log_odds"]}


def validate_case_index(i):
    """Row index of a demo case; raises ValueError for anything that is not a valid index."""
    c = demo_cases()
    n = 0 if c is None else len(c)
    if isinstance(i, bool) or not isinstance(i, (int, np.integer)) or not 0 <= i < n:
        raise ValueError(f"case index must be an integer in [0, {n - 1}]")
    return int(i)


# ------------------------------------------------------------------ methodology
def methodology():
    """Protocol facts for the methodology page, read from the frozen configs and Milestone 3 records."""
    pr, man = protocol(), read_json("configs/feature_manifest_v1.json")
    sel = read_json("configs/model_selection_v1.json")
    purge = read_json("reports/generated/m3_purge.json")
    roles = pd.Series(man["column_class"]).value_counts()
    return {"dataset": pr["source"]["dataset"], "url": pr["source"]["url"], "cleaning": pr["cleaning"],
            "feature_sets": man["feature_set_sizes"], "column_roles": roles.to_dict(),
            "excluded": sorted(k for k, v in man["column_class"].items() if v in ("excluded", "metadata", "target")),
            "experimental": sorted(k for k, v in man["column_class"].items() if v == "experimental"),
            "split": pr["splits"]["primary"], "comparison": pr["splits"]["comparison"],
            "purge": purge["purged_by_reason"], "test_rows_removed_by_purge": purge["test_rows_before_purge"] - purge["test_rows_after_purge"],
            "selection": sel["selection_metric"], "data_use": sel["data_use"], "novel": pr["novel_vector"]["definition"],
            "operating_points": pr["metrics"]["operating_points"], "budgets": [float(b) for b in budgets()]}


# ------------------------------------------------------------------ limitations and formatting
def limitations():
    """Verified limitations, with numbers loaded from the artifacts."""
    r, _ = novel_overview()
    small = small_support_labels()
    fs = fp_story()
    return [
        "Train, validation and test traffic come from the same 2017 lab environment, tools, hosts and scripted runs; "
        "results are within-scenario benchmark results, not evidence of deployment performance.",
        f"{pct(r['attack_near_overlap_share'], 1)} of attack test rows have a near-identical (non-timing) feature "
        f"vector in training, and {pct(r['attack_exact_overlap_share'], 1)} an exact one.",
        "The chronological split is cut per (day, original label) stratum, so its boundaries depend on the labels: "
        "it is retrospective and label-aware, not a deployment-style time split.",
        "Tiny attack classes cannot support stable estimates: "
        + ", ".join(f"{l} ({int(n)} test rows)" for l, n in zip(small.label, small.n)) + ".",
        f"False positives are scenario-dependent: {pct(fs['rev']['fp'] / fs['fp'], 1)} of test false positives are "
        "reverse-direction traffic associated with attack scenarios ("
        + ", ".join(x.capitalize() for x in fs["by_daygroup"].index[fs["by_daygroup"].fp_share_reverse > 0]) + ").",
        "The validation partition was used for early stopping, model selection and threshold choice, so validation "
        "metrics are optimistic.",
        "SHAP values describe the frozen model's behaviour; they are not causal explanations of network attacks, and "
        "another model family (Random Forest) attributes differently.",
        "Labels are used as published (protocol v1); no traffic was relabelled.",
    ]


def pct(x, d=2):
    return NA if x is None or (isinstance(x, float) and np.isnan(x)) else f"{100 * x:.{d}f} %"


def num(x, d=None):
    if x is None or (isinstance(x, float) and np.isnan(x)):
        return NA
    return f"{int(x):,}" if d is None else f"{x:.{d}f}"
