"""Render reports/DATA_AUDIT.md and reports/LEAKAGE_AUDIT.md from reports/generated/*.

Every number in the reports is read from generated files; the prose is fixed text written after
reviewing those files (Milestone 2). If a rerun changes a number, the prose around it must be re-checked.
"""
import json
import sys
from pathlib import Path

import pandas as pd

sys.path.insert(0, str(Path(__file__).resolve().parents[1] / "src"))
from ids.data import DAYS, GENERATED, METADATA, PROVENANCE, REQUIRES_EXPERIMENT, ROOT, TARGET  # noqa: E402

sys.path.insert(0, str(Path(__file__).resolve().parent))
import render_m3  # noqa: E402

R = ROOT / "reports"


def j(name):
    return json.loads((GENERATED / name).read_text())


def c(name):
    return pd.read_csv(GENERATED / name)


def md(df, floatfmt=3):
    df = df.copy()
    for col in df.columns:
        if pd.api.types.is_float_dtype(df[col]):
            df[col] = df[col].map(lambda v: "" if pd.isna(v) else f"{v:.{floatfmt}f}")
    head = "| " + " | ".join(map(str, df.columns)) + " |"
    sep = "|" + "|".join("---" for _ in df.columns) + "|"
    body = ["| " + " | ".join(str(v).replace("|", "\\|") for v in row) + " |" for row in df.itertuples(index=False)]
    return "\n".join([head, sep, *body])


def n(x):
    return f"{int(x):,}"


def pct(x, d=1):
    return f"{100 * x:.{d}f} %"


def load():
    raw = {d: j(f"raw_{d}.json") for d in DAYS}
    return dict(prov=json.loads(PROVENANCE.read_text()), raw=raw, rs=j("raw_summary.json"), lab=j("labels.json"),
                ts=j("timestamps.json"), an=j("anomalies.json"), dup=j("duplicates.json"), ids=j("identifier_summary.json"),
                roles=j("feature_roles.json"), hulk=j("hulk_check.json"), purge=j("purge_cost.json"),
                ep=c("episodes.csv"), win=c("doc_window_check.csv"), lbd=c("labels_by_day.csv"),
                dpl=c("duplicates_per_label.csv"), pairs=c("conflicting_label_pairs.csv"),
                idp=c("identifier_per_attack.csv"), sfb=c("single_feature_binary.csv"),
                sfa=c("single_feature_per_attack_all.csv"), top3=c("single_feature_per_attack_top3.csv"),
                ss=c("split_simulation_summary.csv"), spl=c("split_simulation_per_label.csv"))


# ======================================================================= DATA_AUDIT
def data_audit(D):
    p, raw, lab, ts, an, dup = D["prov"], D["raw"], D["lab"], D["ts"], D["an"], D["dup"]
    header = D["rs"]["header"]
    feats = D["roles"]["candidate_model_features"]
    cat = ["Protocol", "ICMP Code", "ICMP Type"]
    numeric = [f for f in feats if f not in cat]
    out = []
    w = out.append
    w("# Data Audit — improved CIC-IDS2017 (Milestone 2)\n")
    w("Generated by `scripts/render_reports.py` from `reports/generated/*` (produced by `scripts/audit_raw.py` and "
      "`scripts/audit_deep.py`). Do not edit numbers by hand; rerun the scripts.\n")

    w("## 1. Dataset version and provenance\n")
    w(md(pd.DataFrame([
        ("Dataset", f"{p['dataset_name']} — {p['variant']}"),
        ("Source URL", p["source_url"]),
        ("Publication", f"{p['associated_publication']['citation']} doi:{p['associated_publication']['doi']}"),
        ("Archive", f"`{p['archive_filename']}`, {n(p['archive_bytes'])} bytes"),
        ("Archive SHA-256 (computed locally)", f"`{p['archive_sha256']}`"),
        ("Published checksum", "none found — " + p["published_checksum_note"]),
        ("Server Last-Modified / ETag", f"{p['server_headers']['Last-Modified']} / {p['server_headers']['ETag']}"),
        ("Download started (UTC)", p["download_started_utc"]),
        ("ZIP CRC-32 check", p["archive_zip_crc_check"]),
        ("Licence", p["licence_note"]),
        ("Extracted total", f"{n(p['extracted_total_bytes'])} bytes"),
    ], columns=["Field", "Value"])))
    w("\nFull record: `data/DATASET_PROVENANCE.json`.\n")
    files = pd.DataFrame(p["extracted_files"])[["archive_member", "uncompressed_bytes", "sha256"]]
    files["rows"] = files["archive_member"].map({s["file"]: s["rows"] for s in D["rs"]["files"]})
    files["columns"] = files["archive_member"].map({s["file"]: s["columns"] for s in D["rs"]["files"]})
    files["archive_member"] = pd.Categorical(files["archive_member"], [f"{d}.csv" for d in DAYS])
    w(md(files.sort_values("archive_member")[["archive_member", "rows", "columns", "uncompressed_bytes", "sha256"]]))
    w(f"\n**Total rows: {n(D['rs']['total_rows'])}.** Identical header across all files: "
      f"**{D['rs']['identical_headers_across_files']}**.\n")

    w("## 2. Schema (91-column claim)\n")
    w(f"Verified: every file has **{len(header)} columns** with the same names in the same order.\n")
    roles = pd.DataFrame([
        ("Identifier / metadata", len(METADATA), ", ".join(f"`{x}`" for x in METADATA)),
        ("Target / target-derived", len(TARGET), ", ".join(f"`{x}`" for x in TARGET)),
        ("Requires experiment (not in default feature set)", len(REQUIRES_EXPERIMENT), ", ".join(f"`{x}`" for x in REQUIRES_EXPERIMENT)),
        ("Categorical codes (candidate features)", len(cat), ", ".join(f"`{x}`" for x in cat)),
        ("Numeric flow statistics (candidate features)", len(numeric), "all remaining columns"),
    ], columns=["Role", "Count", "Columns"])
    w(md(roles))
    w(f"\nCandidate model features = {len(feats)} (categorical + numeric). This is a *candidate* set, not a final "
      "feature set: several are flagged in `LEAKAGE_AUDIT.md`. Pandas-inferred types (identical on all days): "
      + ", ".join(f"{t}: {sum(1 for v in raw['monday']['dtypes'].values() if v == t)}"
                  for t in sorted(set(raw["monday"]["dtypes"].values()))) + ". String columns: "
      + ", ".join(f"`{k}`" for k, v in raw["monday"]["dtypes"].items() if v == "str") + ".\n")

    w("## 3. Labels\n")
    w(f"Benign **{n(lab['benign'])}**, successful attack **{n(lab['successful_attack'])}**, "
      f"attempted (`... - Attempted`) **{n(lab['attempted'])}**; no unknown or malformed labels "
      f"(unexpected label strings: {lab['unexpected_labels'] or 'none'}). `Attempted Category != -1` exactly when the "
      f"label ends in ` - Attempted`: **{lab['attempted_flag_consistent_with_label_suffix']}**. Only `BENIGN` occurs on "
      "more than one day; every attack label occurs on exactly one day.\n")
    t = D["lbd"].copy()
    t["day"] = pd.Categorical(t["day"], DAYS)
    w(md(t.sort_values(["day", "n"], ascending=[True, False])))
    w("\n### Attempted Category\n")
    w("Codes as defined on the authors' documentation page (CICIDS2017.html): 0 No payload sent by attacker; "
      "1 Port/System closed; 2 Attack startup/teardown artefact; 3 No malicious payload; 4 Attack artefact; "
      "5 Attack implemented incorrectly; 6 Target system unresponsive; −1 not attempted.\n")
    w(md(pd.DataFrame(list(lab["attempted_category_counts"].items()), columns=["Attempted Category", "rows"])))
    w("\nAuthors' instruction (Dataset_Download.html): Attempted flows must *not* be a separate ML class; "
      "\"when in doubt\" relabel them Benign (identify via `Attempted Category != -1`); merging them into the attack "
      "label is left to the researcher. **No relabelling has been applied yet.**\n")
    w("Observed vs documentation: the Friday port scan (documented under \"Infiltration – Portscan, 07-07-2017\") is "
      "labelled **`Portscan`** in the data, while the Thursday scans from the infected host are labelled "
      "**`Infiltration - Portscan`**. `Botnet - Attempted` uses category 1 only.\n")

    w("## 4. Timestamps\n")
    r0 = raw["monday"]["timestamp"]
    w(f"- Column `Timestamp`, string, format `{r0['format_tried']}` (26 characters on every row); parse failures on all "
      f"files: **{sum(raw[d]['timestamp']['parse_failures'] for d in DAYS)}**.\n"
      f"- Timezone suffix present: **{any(raw[d]['timestamp']['has_timezone_suffix'] for d in DAYS)}** → timezone is "
      "**not encoded**.\n"
      "- Consistency evidence (not proof): every successful-attack flow starts inside the authors' documented labelling "
      "window, and those windows are stated in UTC; the daily span (~11:42/12:00 → ~20:00) matches the official 09:00–17:00 "
      "capture if local time is UTC−3 (ADT). Recorded timezone: **unknown, consistent with UTC**.\n"
      "- `Timestamp` is the flow start (first packet), per the authors' \"Time Start (First Packet)\" rules; "
      f"`Flow Duration` (µs) never exceeds {n(max(ts[d]['flow_duration_max_us'] for d in DAYS))} (120 s active timeout).\n")
    tt = pd.DataFrame([{"day": d, "min": ts[d]["min"], "max": ts[d]["max"], "span_h": ts[d]["span_hours"],
                        "file_order_is_time_order": ts[d]["file_order_is_time_order"],
                        "rows_earlier_than_previous": raw[d]["timestamp"]["rows_earlier_than_previous_row"],
                        "max_backward_jump_s": raw[d]["timestamp"]["max_backwards_jump_seconds"],
                        "spearman(file order, time)": ts[d]["spearman_file_order_vs_time"],
                        "rows_with_non_unique_ts": ts[d]["rows_with_non_unique_timestamp"],
                        "largest_gap_s": ts[d]["largest_gap_between_consecutive_flow_starts_s"]} for d in DAYS])
    w(md(tt, 2))
    w("\n**Files are not in time order** (row order is only weakly correlated with time); any chronological "
      "operation must sort by `ts`, never rely on row order. Rows with identical timestamps are concentrated in "
      "high-rate attacks: " + ", ".join(f"{k} {n(v)}" for k, v in list(ts["non_unique_timestamp_rows_by_label"].items())[:5])
      + ". Ties must be broken deterministically (e.g. by `source_file`, `source_row`).\n")
    w("### Documented labelling windows vs data\n")
    w(md(D["win"], 3))

    w("\n## 5. Attack episodes\n")
    w("Per label: first/last flow start, span, number of bursts when consecutive flow starts separated by more than "
      "60 / 300 / 900 s start a new burst, and the three largest gaps (minutes).\n")
    ep = D["ep"][["day", "label", "n", "first", "last_start", "span_min", "src_ips", "dst_ips", "dst_ports",
                  "bursts_gap>60s", "bursts_gap>300s", "bursts_gap>900s", "top_gaps_min"]].copy()
    for col in ("first", "last_start"):
        ep[col] = ep[col].str.slice(11, 19)
    ep["day"] = pd.Categorical(ep["day"], DAYS)
    w(md(ep.sort_values(["day", "first"]), 1))
    succ = D["ep"][~D["ep"]["label"].str.endswith("Attempted")]
    one = succ[succ["bursts_gap>300s"] == 1]
    w(f"\n{len(one)} of {len(succ)} successful-attack labels form a single burst at the 300 s threshold "
      f"({', '.join(sorted(set(succ['label']) - set(one['label'])))} are the exceptions). Every attack label comes "
      "from one day and, for 172.16.0.1-launched attacks, from one attacker host.\n")

    w("## 6. Missing and non-finite values\n")
    w(f"- Missing (NaN/empty) values: **{sum(len(raw[d]['missing_per_column']) + len(raw[d]['empty_string_per_column']) for d in DAYS)}** columns affected on any day (none).\n"
      f"- +inf: {n(an['inf_rate_rows'])} rows in `Flow Bytes/s` and `Flow Packets/s`, all with `Flow Duration` = 0, labels "
      f"{an['inf_rate_labels']}. −inf: none.\n"
      f"- Negative values in non-sentinel columns: `Fwd Header Length` / `Bwd Header Length` on {n(an['negative_header_length_rows'])} rows "
      f"(protocol {list(an['negative_header_length_protocols'])}; labels {an['negative_header_length_labels']}). Both columns are "
      "bounded within [−32,768, 32,767] on every day (per-day min/max: "
      + "; ".join(f"{d} {raw[d]['numeric_summary']['Fwd Header Length']['min']:.0f}…{raw[d]['numeric_summary']['Fwd Header Length']['max']:.0f}" for d in DAYS)
      + "). *Interpretation (unverified):* consistent with signed 16-bit overflow in the extractor, which would also silently "
      "wrap large positive values — these two columns are unreliable for large flows.\n"
      "- `ICMP Code`, `ICMP Type` use −1 as a sentinel for non-ICMP flows; they are never set when `Protocol` ≠ 1 "
      f"(violations: {an['icmp_fields_set_when_protocol_not_1']}). `Attempted Category` uses −1 for not-attempted.\n")

    w("## 7. Duplicates\n")
    w(f"- Exact duplicate rows (all 91 columns, or all but `id`): **{sum(raw[d]['duplicates']['exact_rows_excluding_id'] for d in DAYS)}** on every file. "
      "`id` is 1..n in file order within each file (not globally unique across files).\n"
      f"- `Flow ID` is not a flow identifier: {n(sum(raw[d]['duplicates']['rows_with_repeated_flow_id'] for d in DAYS))} rows share a Flow ID "
      "with another row in the same file (long connections split by the 120 s timeout, and source-port reuse by high-rate tools).\n")
    rows = []
    for key, name in [("features", f"{dup['n_features_hashed']} candidate features"),
                      ("features_plus_dst_port", "candidate features + Dst Port"),
                      ("coarse_no_timing", f"{dup['coarse_feature_count']} non-timing features")]:
        x = dup[key]
        rows.append({"vector definition": name, "distinct vectors": n(x["distinct_vectors"]),
                     "rows in duplicated vectors": n(x["rows_in_duplicated_vectors"]),
                     "redundant rows": n(x["redundant_rows_if_deduplicated"]),
                     "vectors with >1 raw label": n(x["vectors_with_multiple_raw_labels"]),
                     "rows in those": n(x["rows_in_vectors_with_multiple_raw_labels"]),
                     "vectors with conflicting benign/attack*": n(x["vectors_with_conflicting_binary_y"]),
                     "rows in those ": n(x["rows_in_vectors_with_conflicting_binary_y"]),
                     "vectors on >1 day": n(x["vectors_on_multiple_days"])})
    w(md(pd.DataFrame(rows)))
    w("\n\\* binary target with Attempted → Benign (authors' default), used only for this analysis.\n")
    w("\"Non-timing\" drops durations, IATs, rates, active/idle and bulk-rate columns — rows equal on packet counts, sizes, "
      "flags and window fields but differing in timing (a practical *near-duplicate* definition).\n")
    w("### Per label (candidate features)\n")
    w(md(D["dpl"], 3))
    w("\n### Label combinations sharing identical feature vectors\n")
    w(md(D["pairs"]))
    w("\n*Temporal duplicates:* `repeat_within_1s` / `_60s` = share of repeated vectors whose previous identical "
      "occurrence (same label) started within 1 / 60 s. Portscan and Infiltration–Portscan repeat the same probe vector "
      "continuously; DoS/DDoS have no exact duplicates but are near-duplicates once timing is ignored.\n")
    w("**Nothing has been deleted.** Proposed cleaning rule: see §10.\n")

    w("## 8. Constant, near-constant and categorical columns\n")
    const = {d: raw[d]["constant_columns"] for d in DAYS}
    w("Constant per file (includes `Label`/`Attempted Category` on Monday): " +
      "; ".join(f"{d}: {', '.join(v) or '—'}" for d, v in const.items()) + ".\n")
    nc = sorted({k for d in DAYS for k in raw[d]["near_constant_columns"]})
    w(f"Near-constant (top value ≥ 99.9 % of a file's rows) on at least one day: {', '.join(nc)}.\n")
    w("`Protocol` values: " + "; ".join(f"{d} {raw[d]['categorical_values']['Protocol']}" for d in DAYS) + ".\n")
    w("Constant/near-constant columns are **not** dropped here: dropping must be decided on the training split only "
      "(inside the pipeline) to avoid preprocessing leakage.\n")

    w("## 9. Other anomalies\n")
    w(f"- `Protocol` = 0: {n(an['protocol0_rows'])} rows ({an['protocol0_labels']}); most frequent Flow IDs "
      f"{an['protocol0_top_flow_ids']}. Addresses such as `8.6.0.1 → 8.0.6.4` with all ports 0 suggest non-IPv4 frames "
      "parsed as IP (unverified).\n"
      f"- Zero-duration flows: {n(an['zero_duration_rows'])} ({an['zero_duration_labels']}) — exactly the rows with infinite rates.\n"
      f"- DoS Hulk shortcut (Liu et al.): {n(D['hulk']['hulk_rows_with_4_values'])} of {n(D['hulk']['hulk_rows'])} Hulk flows have "
      f"`Total Length of Bwd Packet` ∈ {{11595, 23190, 11606, 23201}} — but so do {n(D['hulk']['non_hulk_rows_with_4_values'])} "
      f"non-Hulk flows ({D['hulk']['non_hulk_labels_with_4_values']}). The values look like response sizes of the victim web "
      "server rather than a Hulk-specific signature.\n"
      "- Label taxonomy: `Portscan` (Friday) and `Infiltration - Portscan` (Thursday) share identical feature vectors "
      f"({n(D['pairs'].loc[D['pairs']['pair'] == 'Infiltration - Portscan + Portscan', 'rows'].sum())} rows) — the same "
      "scanning behaviour under two names.\n")

    w("## 10. Recommended cleaning (Milestone 2 proposal — implementation status in §11)\n")
    w("| # | Rule | Rationale |\n|---|---|---|\n"
      f"| 1 | Keep all {n(D['rs']['total_rows'])} rows in `data/interim`; apply every rule below in a derived table only | raw/interim stay complete for audit |\n"
      "| 2 | Label policy: Attempted → Benign (primary); ablation: drop Attempted rows | authors' stated default; alternative required by their note that the choice depends on preprocessing |\n"
      f"| 3 | Drop the {n(an['inf_rate_rows'])} zero-duration rows with infinite rates (all Benign) | undefined rates; negligible count; avoids an imputation choice |\n"
      "| 4 | Do **not** globally de-duplicate. Keep repeated vectors in training data; evaluate on the full test set **and** on the test rows whose feature vector never occurs in training | repeated scans are real traffic; deleting them changes class priors, but test rows seen in training measure memorisation |\n"
      "| 5 | Keep conflicting-label vectors; report their count as a label-noise floor | cannot be resolved from flow features |\n"
      "| 6 | Constant / near-constant columns: drop only if constant in the training split, inside the pipeline | preprocessing leakage |\n"
      "| 7 | `Fwd/Bwd Header Length`: keep raw, flag as unreliable; ablation without them | probable 16-bit overflow |\n"
      "| 8 | `Protocol` = 0 rows: keep, flag (open question) | cause unverified |\n"
      "| 9 | Multiclass only: merge `Infiltration - Portscan` into a `Portscan` family, or report the pair explicitly | identical vectors under two labels |\n"
      "| 10 | Sort by (`ts`, `source_file`, `source_row`) before any chronological operation | files are not time-ordered; ties exist |\n")
    return "\n".join(out)


# ======================================================================= LEAKAGE_AUDIT
def leakage_audit(D):
    ids, sfb, sfa, ss, spl, dup = D["ids"], D["sfb"], D["sfa"], D["ss"], D["spl"], D["dup"]
    b = sfb.set_index("feature")["bal_acc_binary"]
    piv = sfa.pivot(index="label", columns="feature", values="bal_acc")
    out = []
    w = out.append
    w("# Leakage Audit — improved CIC-IDS2017 (Milestone 2)\n")
    w("Generated by `scripts/render_reports.py` from `reports/generated/*`. Exploratory screening only; no model has been "
      "trained or evaluated. Each section separates **Observed evidence** from **Interpretation / possible risk**.\n")
    w("Screening method: for each column, a one-feature classifier fitted on a random half and scored (balanced accuracy, "
      "0.5 = chance) on the other half — a depth-3 decision tree for numeric columns, a value→majority-label lookup for "
      "identifier columns. Binary target: attack vs benign with Attempted → Benign. Per-attack: that label vs a fixed 50k "
      "sample of same-day benign flows. Mutual information on a 50k/50k stratified sample. Random halves make these "
      "scores optimistic by construction (duplicates), which is acceptable for *flagging*.\n")

    w("## 1. Feature classification\n")
    def bl(f):
        return f"{b[f]:.3f}" if f in b else "—"
    cls = [
        ("`Label`", "TARGET", "Primary target (binary / multiclass derived from it)."),
        ("`Attempted Category`", "TARGET", "Target-derived: set by the labelling logic, non-(−1) exactly on `- Attempted` labels. Used only to implement the label policy; never a feature."),
        ("`id`", "METADATA ONLY", f"Row number in file (1..n); stable record id together with `source_file`. Weakly predictive through file order (binary {bl('id')})."),
        ("`source_file`, `source_row`", "METADATA ONLY", "Provenance added by us; day determines which attacks exist."),
        ("`Timestamp` / `ts`", "METADATA ONLY", f"Needed for splitting. Alone it separates attacks from same-day benign (per-attack {piv['t'].min():.2f}–{piv['t'].max():.2f}) because each attack occupies one window. No time-of-day features."),
        ("`Flow ID`", "METADATA ONLY", f"Concatenation of IPs, ports, protocol; not unique (binary {bl('Flow ID')}). Not a valid grouping key (port reuse)."),
        ("`Src IP`", "EXCLUDED DUE TO LEAKAGE RISK", f"172.16.0.1 is the source of {pct(ids['attack_rows_from_172.16.0.1_share'])} of successful-attack rows but only {ids['labels_src_172.16.0.1'].get('BENIGN', 0)} benign rows; per-attack score 1.0 for every 172.16.0.1 attack. Kept as metadata for audits."),
        ("`Dst IP`", "EXCLUDED DUE TO LEAKAGE RISK", f"Best single binary separator of all columns ({bl('Dst IP')}); victims are fixed hosts (192.168.10.50/.51, 205.174.165.73)."),
        ("`Src Port`", "EXCLUDED DUE TO LEAKAGE RISK", f"Ephemeral; the authors' labelling rules use specific source ports (e.g. Heartbleed 45022: per-attack {piv.loc['Heartbleed', 'Src Port']:.2f})."),
        ("`Dst Port`", "REQUIRES EXPERIMENT", f"Service semantics are legitimate, but attacks target fixed ports (binary {bl('Dst Port')}; Heartbleed 444 and Botnet 8080 {piv.loc['Heartbleed', 'Dst Port']:.2f}/{piv.loc['Botnet', 'Dst Port']:.2f}). With/without ablation."),
        ("`Protocol`", "MODEL FEATURE", f"Four codes (0, 1, 6, 17); not separating on its own (binary {bl('Protocol')})."),
        ("`FWD Init Win Bytes`, `Bwd Init Win Bytes`, `Fwd Seg Size Min`", "REQUIRES EXPERIMENT", "Host/OS TCP configuration rather than behaviour (hypothesis); Bwd Init Win Bytes ≥0.99 for Hulk, DDoS, SSH-Patator. Ablation."),
        ("`Fwd Header Length`, `Bwd Header Length`", "REQUIRES EXPERIMENT", "Probable 16-bit overflow (DATA_AUDIT §6)."),
        ("Backward size features (`Total Length of Bwd Packet`, `Bwd Packet Length *`, `Subflow Bwd Bytes`, …)", "MODEL FEATURE (flagged)", "Top binary separators; encode the victim server's response sizes (DoS Hulk/DDoS share four exact values). Watch in SHAP."),
        ("All other CICFlowMeter statistics, `ICMP Code`, `ICMP Type`", "MODEL FEATURE", "Flow behaviour; constant columns handled inside the pipeline."),
    ]
    w(md(pd.DataFrame(cls, columns=["Column(s)", "Class", "Reason"])))

    w("\n## 2. Direct target leakage\n")
    w("**Observed evidence.** `Attempted Category` is non-(−1) on exactly the `- Attempted` labels "
      f"(consistency check: {D['lab']['attempted_flag_consistent_with_label_suffix']}). No other column is a copy of the label.\n")
    w("**Interpretation / risk.** Including `Attempted Category` would leak the label policy itself. Excluded by `model_features()` "
      "and asserted in `tests/test_basics.py` and `tests/test_dataset.py`.\n")

    w("## 3. Identifier leakage\n")
    w("**Observed evidence.**\n")
    w(md(D["idp"], 4))
    w("\nSingle-identifier balanced accuracy per attack (vs same-day benign):\n")
    w(md(piv[["Src IP", "Dst IP", "Src Port", "Dst Port", "Protocol", "t"]].reset_index(), 3))
    w("\n**Interpretation / risk.** The labels were *constructed* from IP, port and time rules (authors' labelling logic), "
      "so any of these columns lets a model reproduce the labelling rule rather than detect behaviour. Botnet and "
      "Infiltration sources are ordinary victim hosts that also generate benign traffic, so for those, `Src IP` is weak "
      "but `Dst IP`/`Dst Port` (the C2 server) are perfect. Excluding IPs does not remove host identity entirely: "
      "TCP-stack fields (§1) may re-encode it.\n")

    w("## 4. Temporal leakage\n")
    w("**Observed evidence.** Every attack label lives in one contiguous window on one day (DATA_AUDIT §5); files are not "
      "time-ordered; flows last up to 120 s, so a flow starting before a split point can overlap flows after it. Repeated "
      "identical vectors in scans recur within ≤ 1 s (DATA_AUDIT §7).\n")
    w("**Interpretation / risk.** A random split places each test flow next to near-identical training flows from the same "
      "second. Time itself is a near-perfect attack indicator within a day, so no time-derived feature may be used.\n")

    w("## 5. Duplicate leakage and split simulation\n")
    w("**Observed evidence.** Candidate 70/30 designs simulated on the full data (no model): share of test rows whose exact "
      "feature vector (or non-timing vector, or Flow ID) also occurs in training. Weighted over labels.\n")
    w(md(ss, 3))
    w(f"\nPurging (A_chrono_purged_train) removes {n(D['purge']['train_rows_purged'])} training rows "
      f"({n(D['purge']['attack_train_rows_purged'])} attack) whose flow interval reaches past the per-label cut; "
      "the embargo variants instead discard test rows that start within E s after the cut.\n")
    key = ["Portscan", "Infiltration - Portscan", "DoS Hulk", "DDoS", "DoS GoldenEye", "DoS Slowloris", "FTP-Patator",
           "SSH-Patator", "Botnet", "Heartbleed", "Infiltration", "Web Attack - XSS", "Web Attack - SQL Injection",
           "Web Attack - Brute Force", "BENIGN"]
    sub = spl[spl["label"].isin(key) & spl["strategy"].isin(["D_random_stratified", "A_chrono_within_label",
                                                              "A_chrono_purged_train", "A_chrono_embargo_120s",
                                                              "B_burst_holdout_last_burst"])]
    w("\nPer label (selected labels, all strategies in `reports/generated/split_simulation_per_label.csv`):\n")
    w(md(sub[["strategy", "label", "n_train", "n_test", "test_vector_in_train_any_label", "test_coarse_vector_in_train",
              "median_s_to_nearest_train_same_label"]], 3))
    w("\n**Interpretation / risk.**\n"
      "- The chronological within-label split does **not** reduce exact-duplicate overlap relative to a random split: "
      "the overlap comes almost entirely from Portscan / Infiltration–Portscan, whose identical probe vectors recur across "
      "the whole episode, not only near the boundary. It does move test flows away in time (median distance to the nearest "
      "same-label training flow rises from ~0 s to tens–hundreds of seconds).\n"
      "- DoS/DDoS have no exact duplicates, but most test rows match a training row on every non-timing feature under "
      "*any* within-episode split → the test set measures recognition of the same tool run (scenario memorisation), "
      "which no split inside a single episode can remove.\n"
      "- A 120 s test-side embargo discards a large share of test rows of the short DoS/DDoS episodes while leaving the "
      "duplicate overlap nearly unchanged; 600 s removes whole test portions. Purging training flows costs far less and "
      "removes the interval overlap.\n"
      "- Burst holdout (B) degenerates to A for single-burst labels and produces extreme partitions where it applies "
      "(see Infiltration–Portscan, SSH-Patator rows). Episode holdout (C) is infeasible: most labels have one episode.\n")

    w("## 6. Preprocessing leakage risks\n")
    w("**Observed evidence.** Constant columns differ by day (DATA_AUDIT §8); infinite rates exist; class priors differ "
      "strongly by day.\n")
    w("**Interpretation / risk.** Any scaler, imputer, constant-column filter, feature selector or resampler must be fitted "
      "on training rows only (sklearn `Pipeline`). Deduplication decisions must use training rows only. Thresholds must be "
      "chosen on a validation slice carved chronologically from the training portion.\n")

    w("## 7. Scenario-specific artefacts\n")
    hk = D["hulk"]
    w(f"**Observed evidence.** Hulk four-value filter: {n(hk['hulk_rows_with_4_values'])}/{n(hk['hulk_rows'])} Hulk rows, plus "
      f"{n(hk['non_hulk_rows_with_4_values'])} non-Hulk rows ({hk['non_hulk_labels_with_4_values']}). Per-attack single-feature "
      "top-3 (candidate features only):\n")
    w(md(D["top3"][["label", "n_attack", "feature", "bal_acc"]], 4))
    w("\n**Interpretation / risk.** Almost every attack has at least one candidate feature that alone separates it from "
      "same-day benign traffic at ≥ 0.99. High single-feature predictiveness is *expected* for scripted attacks against one "
      "server and is not by itself leakage; but it means reported accuracy will mostly reflect tool/server signatures of "
      "this testbed (e.g. victim response sizes), not transferable detection. These features are flagged for SHAP review "
      "and ablation, not removed.\n")

    w("## 8. Suspicious predictive features (binary screening, top 25)\n")
    w(md(sfb.head(25), 3))
    w("\n`n_attacks_bal_acc>=0.99` = number of attack labels for which that column alone reaches ≥ 0.99 vs same-day benign.\n")

    w("## 9. Proposed mitigations\n")
    w("1. Exclude `Src IP`, `Dst IP`, `Src Port`, `Flow ID`, `id`, `Timestamp`, provenance columns and `Attempted Category` from features (enforced in code + tests).\n"
      "2. `Dst Port`, TCP-stack fields and header-length fields: with/without ablations.\n"
      "3. Primary split: chronological within each (day, label) stratum with training-side purging (see recommendation below).\n"
      "4. Report metrics on the full test set and on the *novel-vector* test subset (feature vector never seen in training).\n"
      "5. Random stratified split only as a labelled optimistic baseline; held-out-attack experiment reported separately.\n"
      "6. All preprocessing inside a train-fitted pipeline; tests assert fitted transformers only see training indices.\n"
      "7. Never claim the dataset or the evaluation is leakage-free: scenario memorisation remains (§5).\n")
    w("## 10. Validation design — evaluation of candidates and recommendation\n")
    a = ss.set_index(["strategy", "part"])
    ov = lambda st: a.loc[(st, "attacks"), "test_vector_in_train_any_label"]  # noqa: E731
    co = lambda st: a.loc[(st, "attacks"), "test_coarse_vector_in_train"]  # noqa: E731
    w("(`attacks` in the split tables = all non-benign raw labels, including `- Attempted`.)\n")
    w("| Candidate | Evidence from this data | Verdict |\n|---|---|---|\n"
      f"| A. Chronological 70/30 within each (day, label) | test overlap {ov('A_chrono_within_label'):.3f} exact / {co('A_chrono_within_label'):.3f} non-timing vs random {ov('D_random_stratified'):.3f} / {co('D_random_stratified'):.3f}; moves test later in time; every label present in train | Usable as the base, **not sufficient alone** |\n"
      f"| A + test-side embargo 120 s / 600 s | attack test rows {n(a.loc[('A_chrono_embargo_120s', 'attacks'), 'n_test'])} / {n(a.loc[('A_chrono_embargo_600s', 'attacks'), 'n_test'])} of {n(a.loc[('A_chrono_within_label', 'attacks'), 'n_test'])}; overlap barely changes | Rejected: large test loss, little benefit |\n"
      f"| A + training-side purge | {n(D['purge']['train_rows_purged'])} training rows removed; no test loss; removes flow-interval overlap across the cut | **Adopt** |\n"
      f"| B. Burst (grouped temporal) holdout | most labels have one burst; where several exist the partition is extreme | Rejected as primary |\n"
      "| C. Episode holdout | needs ≥ 2 independent episodes per label; not available | Infeasible |\n"
      "| D. Random stratified | median 0 s to nearest same-label train flow; exact/non-timing overlap about equal to A | Optimistic baseline only |\n"
      "| E. Held-out attack family | only way to probe beyond the scripted run | Separate experiment, not the benchmark |\n")
    w("\n**Recommended primary design (proposal for review):** chronological 70/30 split by flow start within every "
      "(day, raw label) stratum — including each day's benign traffic and the `- Attempted` flows — with training rows purged "
      "when their flow interval reaches past the stratum's cut; ties ordered by (`ts`, `source_file`, `source_row`); "
      "hyper-parameters tuned on a chronological slice of the training part only; metrics reported on (a) the full test set "
      "and (b) the *novel-vector* test subset; classes with < 30 test rows reported with counts and flagged.\n")
    w("**Why:** each attack exists in a single episode on a single day, so a supervised benchmark must train and test inside "
      "episodes; chronology keeps test data strictly later; purging removes interval overlap at negligible cost; the "
      "novel-vector subset handles the duplicate leakage that chronology cannot. **Known limitation:** train and test "
      "share tool, attacker, victim and run — non-timing overlap stays high — so results estimate within-scenario forward "
      "generalisation and remain optimistic. The random split (D) quantifies that optimism; E is reported separately.\n")
    return "\n".join(out)


def data_card_block(D):
    p, lab, an, dup = D["prov"], D["lab"], D["an"], D["dup"]
    rows = [("Compressed zip", f"{n(p['archive_bytes'])} bytes (SHA-256 `{p['archive_sha256']}`)"),
            ("Uncompressed CSVs", f"{n(p['extracted_total_bytes'])} bytes"),
            ("Rows per day", ", ".join(f"{s['file'].removesuffix('.csv')} {n(s['rows'])}" for s in D["rs"]["files"])),
            ("Rows total", n(D["rs"]["total_rows"])),
            ("Columns", f"{len(D['rs']['header'])} (identical on all days); {D['roles']['n']} candidate features"),
            ("Benign / successful attack / attempted", f"{n(lab['benign'])} / {n(lab['successful_attack'])} / {n(lab['attempted'])}"),
            ("Missing values", n(sum(sum(D["raw"][d]["missing_per_column"].values()) for d in DAYS))),
            ("Infinite values", f"{n(an['inf_rate_rows'])} rows (`Flow Bytes/s`, `Flow Packets/s`; zero-duration flows)"),
            ("Exact duplicate rows", n(sum(D["raw"][d]["duplicates"]["exact_rows_excluding_id"] for d in DAYS))),
            ("Duplicate feature vectors", f"{n(dup['features']['redundant_rows_if_deduplicated'])} redundant rows; "
                                          f"{n(dup['features']['rows_in_vectors_with_conflicting_binary_y'])} rows in benign/attack-conflicting vectors"),
            ("Timestamp timezone", "not encoded; consistent with UTC (unverified)"),
            *render_m3.card_rows(D["m3"], n)]
    lc = pd.DataFrame(list(lab["label_counts"].items()), columns=["Label", "rows"])
    return (md(pd.DataFrame(rows, columns=["Measure", "Value"])) + "\n\nLabel counts (all days):\n\n" + md(lc))


def main():
    D = load()
    D["m3"] = M = render_m3.load_m3()
    (R / "DATA_AUDIT.md").write_text(data_audit(D) + render_m3.data_audit_m3(M, md, n) + "\n")
    (R / "LEAKAGE_AUDIT.md").write_text(leakage_audit(D) + render_m3.leakage_audit_m3(M, md, n) + "\n")
    (R / "EXPERIMENT_PROTOCOL.md").write_text(render_m3.protocol_doc(M, md, n) + "\n")
    card = ROOT / "DATA_CARD.md"
    s = card.read_text()
    a, b = "<!-- BEGIN GENERATED (scripts/render_reports.py) -->", "<!-- END GENERATED -->"
    card.write_text(s[: s.index(a) + len(a)] + "\n" + data_card_block(D) + "\n" + s[s.index(b):])
    print("wrote reports and", card)


if __name__ == "__main__":
    main()
