"""Milestone 3 report sections, rendered from configs/*_v1.json and reports/generated/m3_*.

Called by render_reports.py. Numbers come from generated files; prose was written after reviewing them.
"""
import json

import pandas as pd

from ids.data import GENERATED, ROOT


def _j(p):
    return json.loads(p.read_text())


def load_m3():
    c = lambda n: pd.read_csv(GENERATED / n)  # noqa: E731
    return dict(protocol=_j(ROOT / "configs/experiment_protocol_v1.json"), manifest=_j(ROOT / "configs/feature_manifest_v1.json"),
                labels=_j(ROOT / "configs/label_mapping_v1.json"), cleaning=_j(GENERATED / "m3_cleaning.json"),
                purge=_j(GENERATED / "m3_purge.json"), removed=c("m3_removed_rows.csv"), fam=c("m3_family_distribution.csv"),
                acc=c("m3_partition_counts.csv"), nsum=c("m3_novel_summary.csv"), nlab=c("m3_novel_by_label.csv"),
                cross=c("m3_cross_stratum_overlap.csv"), day=c("m3_day_overlap.csv"), bnd=c("m3_split_boundaries_chrono.csv"))


def _totals(M, protocol):
    a = M["acc"][M["acc"].protocol == protocol]
    t = a.groupby(["partition", "y_binary"])["n"].sum().unstack("y_binary").fillna(0).astype(int)
    t.columns = ["benign (y=0)", "attack (y=1)"]
    t["total"] = t.sum(axis=1)
    return t.reindex([p for p in ["train", "val", "test", "purged"] if p in t.index]).reset_index()


def protocol_doc(M, md, n):
    P, man, cl, pu = M["protocol"], M["manifest"], M["cleaning"], M["purge"]
    out = []
    w = out.append
    w("# Experiment Protocol v1 — improved CIC-IDS2017\n")
    w("Generated by `scripts/render_reports.py` from `configs/experiment_protocol_v1.json`, `configs/feature_manifest_v1.json`, "
      "`configs/label_mapping_v1.json` and `reports/generated/m3_*` (all produced by `scripts/prepare.py`). "
      f"Status: **{P['status']}**. No model has been trained under this protocol yet.\n")
    w("## 1. What this evaluation measures — and what it does not\n")
    w("**Measures:** how well a flow-feature classifier trained on the earlier part of each labelled traffic stratum "
      "(each attack episode and each day's benign traffic) recognises flows from the later part of the *same* stratum, in the "
      "*same* 2017 testbed, with the same attacker, victims and tools, and — separately — on test flows whose exact feature "
      "vector never occurs in training.\n")
    w("**Does not measure:** detection on independent networks, independent attack campaigns, unseen attack types, or real "
      "future traffic; deployment performance; robustness to adversaries. The split is built *within* (day, label) groups, "
      "i.e. it uses the labels retrospectively to decide where each group is cut — a deployed detector never knows where an "
      "attack episode starts or ends. Training data therefore includes traffic that is later in wall-clock time than some test "
      "traffic of the same day (§6). Results must never be described as real-world or deployment performance.\n")
    w("## 2. Source\n")
    w(md(pd.DataFrame([("Dataset", P["source"]["dataset"]), ("URL", P["source"]["url"]),
                       ("Archive SHA-256", f"`{P['source']['archive_sha256']}`")] +
                      [(f"`{k}` SHA-256", f"`{v}`") for k, v in P["source"]["files"].items()], columns=["Item", "Value"])))
    w("\n## 3. Cleaning (applied)\n")
    w(f"- Input {n(cl['rows_in'])} rows → removed **{n(cl['rows_removed_non_finite'])}** → **{n(cl['rows_out'])}** rows. "
      f"Rule: {cl['removed_rule']}. Re-audited in `prepare.py` (aborts if the count or labels differ from Milestone 2). Removed rows:\n")
    w(md(M["removed"]))
    w(f"\n- Kept and flagged: `Protocol == 0` ({n(cl['kept_flag_protocol0'])} rows, {cl['kept_flag_protocol0_by_label']}); negative "
      f"header lengths ({n(cl['kept_flag_negative_header_length'])} rows, {cl['kept_flag_negative_header_length_by_label']}). Their "
      "cause is unverified (DATA_AUDIT §6, §9); they are not demonstrably invalid flows, so they stay. The header-length "
      "fields are the subject of the `no_header_length` ablation.\n"
      "- Duplicates: **no rows deleted**. Duplicate leakage is handled by the novel-vector evaluation (§7).\n")
    w("## 4. Targets and label mappings\n")
    L = M["labels"]
    w(f"- Binary: {L['binary_positive_class']}. Source: {L['binary_rule_source']}.\n- Multiclass `family`: {L['family_rule']}\n"
      f"- Sensitivity variant `excl_attempted`: {L['sensitivity_variant']}.\n- Original `Label` and `Attempted Category` are kept "
      "unchanged in the dataset (`label_original` duplicates `Label` for reporting), so every result can be broken down by the "
      "original labels, including `Portscan` vs `Infiltration - Portscan` inside the unified `Portscan` family.\n")
    w(md(pd.DataFrame(L["labels"])))
    w("\n**Implications of the two Attempted treatments.** *Relabel as benign (primary):* matches the authors' default; the "
      "detector is asked not to alert on payload-less or failed attack flows, which is realistic for a behaviour-based detector "
      "but penalises alerts on traffic that did come from the attacker. *Exclude (sensitivity):* removes ambiguous flows from "
      "training and evaluation, which makes the task cleaner but slightly easier and less representative. Comparing both shows "
      "how much results depend on this labelling choice.\n")
    w("## 5. Features\n")
    w(f"Manifest: `configs/feature_manifest_v1.json`. Every one of the {len(man['column_class'])} raw columns has exactly one class:\n")
    cc = pd.Series(man["column_class"])
    w(md(pd.DataFrame([(k, int((cc == k).sum()), ", ".join(f"`{c}`" for c in cc[cc == k].index) if k != "default" else "see below")
                       for k in ["target", "metadata", "excluded", "experimental", "default"]], columns=["Class", "Columns", "Names"])))
    w("\nColumns added during preparation are never model inputs: " + ", ".join(f"`{c}`" for c in man["added_columns_never_features"]) + ".\n")
    d = man["feature_sets"]["default"]
    w(f"\n**Default feature set ({len(d)}):** " + ", ".join(f"`{c}`" for c in d) + ".\n")
    rows = [("default", len(d), "all default columns"),
            ("default_plus_dst_port", len(man["feature_sets"]["default_plus_dst_port"]), "+ `Dst Port` (experimental; service semantics vs fixed attack targets)"),
            ("no_tcp_window", len(man["feature_sets"]["no_tcp_window"]), "− `FWD Init Win Bytes`, `Bwd Init Win Bytes` (possible host/OS artefacts)"),
            ("no_header_length", len(man["feature_sets"]["no_header_length"]), "− `Fwd Header Length`, `Bwd Header Length` (probable 16-bit overflow)")]
    w(md(pd.DataFrame(rows, columns=["Feature set", "Size", "Difference from default"])))
    w("\nNot generated: other combinations (not justified by the audit). `Fwd Seg Size Min` — grouped with the TCP-stack fields "
      "in LEAKAGE_AUDIT §1 — stays in the default set because the approved ablation names only the two window fields; it remains "
      "flagged for SHAP review. Selection is by name only (`check_features()` rejects target, metadata, excluded and added columns).\n")
    w("## 6. Splits\n")
    sp = P["splits"]["primary"]
    w(f"**Primary (`chrono`).** Strata: {sp['strata']}. Order: {sp['order']}. Sizes: {sp['sizes']}. Purge: {sp['purge']}\n")
    w("**Why chronological:** each attack exists as a single episode on a single day (DATA_AUDIT §5), so a supervised "
      "benchmark has to train and test inside episodes; ordering by time keeps every test flow later than its stratum's "
      "training flows, and purging removes flows whose time interval (up to 120 s) crosses a boundary. Chronology alone does "
      "not reduce exact-duplicate overlap (LEAKAGE_AUDIT §5), hence §7.\n")
    w("**Validation partition:** the last ~20 % (before test) of each stratum's pre-test part; chronologically after train and "
      "before test in every stratum. A single global time cut per day was not used: attacks occupy short windows, so a day-level "
      "cut would put whole attack types only in train or only in test. Compromises (measured): rare classes get 2–9 validation "
      "rows (Heartbleed 2, SQL Injection 2, XSS 2, Infiltration 5, Brute Force 9) — useless for per-class tuning; thresholds are "
      "therefore selected on the binary task only. Purging shrinks some validation sets strongly because those attacks keep "
      "long connections open (see table).\n")
    w(f"Purge result: {n(sum(pu['purged_by_reason'].values()))} rows removed ({pu['purged_by_reason']}); test rows before/after purge: "
      f"{n(pu['test_rows_before_purge'])}/{n(pu['test_rows_after_purge'])}; checks train-ends-before-val "
      f"{pu['check_train_ends_before_val']}, val-ends-before-test {pu['check_val_ends_before_test']}.\n")
    w(md(pd.DataFrame(pu["purged_by_label"])))
    w("\n**Partition sizes (chrono):**\n")
    w(md(_totals(M, "chrono")))
    w("\n**By family and partition** (`test_unstable` = fewer than 30 test rows → class-specific estimates flagged unstable):\n")
    w(md(M["fam"]))
    w("\nPer-stratum boundaries (first/last flow start per partition): `reports/generated/m3_split_boundaries_chrono.csv`. "
      "Row-level manifests: `data/processed/split_chrono_v1.parquet`, `split_random_v1.parquet` (git-ignored; content hashes in §10).\n")
    w("**Retrospective, not a deployment simulation (measured):** training rows of other strata that start *after* the first "
      "test flow of an attack stratum on the same day:\n")
    w(md(M["cross"]))
    w("\nPer day:\n")
    w(md(M["day"]))
    w("\n**Comparison (`random`).** Same strata and per-stratum sizes, random order (seed "
      f"{P['splits']['comparison']['seed']}), no purge, same features and preprocessing. Its purpose is to measure how much the "
      "evaluation protocol changes the numbers; no direction of the difference is assumed.\n")
    w(md(_totals(M, "random")))
    w("\n## 7. Novel-vector test subset\n")
    nv = P["novel_vector"]
    w(f"- Definition: {nv['definition']}.\n- Reference set: {nv['reference_set']}.\n- Near-duplicates: {nv['near_duplicate_definition']}.\n"
      "- Recomputed for every (protocol, label variant, feature set); stored as boolean columns in "
      "`data/processed/novel_test_v1.parquet`.\n- It is **not** unseen-attack detection and **not** independent-network "
      "generalisation: every novel test flow still comes from an attack type, host and tool present in training.\n")
    w(md(M["nsum"], 3))
    nl = M["nlab"]
    nl = nl[(nl.protocol == "chrono") & (nl.variant == "primary") & (nl.feature_set == "default")]
    w("\nBy original label (chrono, primary, default features):\n")
    w(md(nl[["label_original", "family", "full", "exact_seen", "novel", "exact_overlap_share", "near_overlap_share", "novel_unstable"]], 3))
    w("\nExact overlap is concentrated in the two scan labels; every other attack label has no exact duplicate in training, "
      "but most have high *near*-duplicate overlap (identical on all non-timing features). The novel subset therefore changes the "
      "attack mix drastically (scans almost disappear) — compare per-family results, not only the pooled number. All other "
      "feature sets / variants: `reports/generated/m3_novel_by_label.csv`.\n")
    w("## 8. Preprocessing and model selection\n")
    w(f"- {P['preprocessing']}.\n- {P['model_selection']}.\n- Models are fitted on `train` only in v1 (not re-fitted on train+val), so the "
      "novel-vector reference set is exactly the fitted data.\n")
    w("## 9. Metrics (defined in `src/ids/metrics.py`)\n")
    m = P["metrics"]
    w(f"- Positive class / score: {m['positive_class']}.\n- Threshold-free: {'; '.join(m['threshold_free'])}.\n"
      f"- Operating points: {m['operating_points']}. Two false-alarm budgets are fixed now, before any result exists, because a "
      "detector's usefulness depends on false alarms at realistic volumes (at ~478k benign test flows, 0.1 % ≈ 478 false alerts).\n"
      f"- At each threshold: {', '.join(m['at_threshold'])}.\n- Multiclass: {m['multiclass']}.\n- Undefined values: {m['undefined']}.\n"
      f"- Support below {m['unstable_support_below']}: flagged unstable.\n- Evaluation sets: {', '.join(m['evaluation_sets'])}.\n"
      "- No single metric is the optimisation target: PR-AUC summarises the attack class but hides the false-alarm volume; "
      "the FPR-budgeted operating points make that trade-off explicit.\n")
    w("## 10. Planned experiments and artifacts\n")
    w("\n".join(f"- {e}" for e in P["experiments_planned"]) + "\n")
    w(md(pd.DataFrame([(k, v.get("rows", ""), v.get("content_sha256", v.get("sha256"))) for k, v in P["artifacts"].items()],
                      columns=["Artifact", "Rows", "SHA-256 (content hash for Parquet, file hash for JSON)"])))
    w("\nParquet hashes are over the values (`pandas.util.hash_pandas_object`), so they do not depend on Parquet library metadata.\n")
    w("## 11. Versioning rule\n")
    w("This protocol is frozen before training. Any change (cleaning, features, split, metrics, thresholds) creates "
      "`experiment_protocol_v2.json` with a written reason; v1 artifacts are not overwritten. The split must not be changed after "
      "test results have been seen.\n")
    return "\n".join(out)


def data_audit_m3(M, md, n):
    cl = M["cleaning"]
    return "\n".join([
        "\n## 11. Milestone 3 — cleaning status\n",
        md(pd.DataFrame([
            ("Drop non-finite rows", f"applied: {n(cl['rows_removed_non_finite'])} rows (re-audited; list in `m3_removed_rows.csv`)"),
            ("Attempted → Benign (primary) / exclude (sensitivity)", "applied as targets `y_binary` and variant `excl_attempted`; originals kept"),
            ("No global de-duplication; novel-vector test subset", "applied (EXPERIMENT_PROTOCOL §7)"),
            ("Keep conflicting-label vectors", "applied (kept)"),
            ("Constant columns dropped only on training data", "implemented in `src/ids/pipeline.py`"),
            ("Header lengths kept + ablation", f"applied; {n(cl['kept_flag_negative_header_length'])} rows flagged"),
            ("Protocol 0 kept + flag", f"applied; {n(cl['kept_flag_protocol0'])} rows flagged"),
            ("Unified Portscan family (multiclass only)", "applied in `family`; original labels kept"),
            ("Sort by (ts, source_file, source_row)", "applied in all chronological operations"),
        ], columns=["Rule (§10)", "Status"])),
        f"\nCleaned dataset: **{n(cl['rows_out'])} rows** (`data/processed/dataset_v1.parquet`, git-ignored).\n"])


def leakage_audit_m3(M, md, n):
    s = M["nsum"].set_index(["protocol", "variant", "feature_set"])
    a, r, d = (s.loc[k] for k in [("chrono", "primary", "default"), ("random", "primary", "default"),
                                   ("chrono", "primary", "default_plus_dst_port")])
    fri = M["day"].set_index("day").loc["friday"]
    return "\n".join([
        "\n## 11. Milestone 3 — implemented safeguards and measured residual risk\n",
        "**Observed evidence (implemented split, `configs/experiment_protocol_v1.json`).**\n",
        f"- Purging removed {n(sum(M['purge']['purged_by_reason'].values()))} train/val rows; no test row changed.\n"
        f"- Exact overlap of attack test rows with training: chrono {a.attack_exact_overlap_share:.3f}, random "
        f"{r.attack_exact_overlap_share:.3f}; near (non-timing) overlap {a.attack_near_overlap_share:.3f} vs "
        f"{r.attack_near_overlap_share:.3f}. With `Dst Port` added the exact overlap is {d.attack_exact_overlap_share:.3f} — "
        "novelty depends on the feature set, so it is recomputed per set.\n"
        f"- Friday: {n(fri.train_rows_starting_after_first_test)} of {n(fri.train_rows)} training rows start after the first Friday test flow.\n",
        "**Interpretation / possible risk.** The implemented design removes interval overlap and makes duplicate overlap "
        "measurable, but it does not remove scenario memorisation (same tools, hosts and run in train and test) and it uses "
        "label-defined strata. The dataset and this evaluation are **not** leakage-free; results are within-scenario estimates. "
        "Details: `reports/EXPERIMENT_PROTOCOL.md`.\n"])


def card_rows(M, n):
    cl, man = M["cleaning"], M["manifest"]
    t = _totals(M, "chrono").set_index("partition")
    return [("Final rows (after cleaning)", f"{n(cl['rows_out'])} ({n(cl['rows_removed_non_finite'])} non-finite rows removed)"),
            ("Model feature sets", ", ".join(f"{k} {v}" for k, v in man["feature_set_sizes"].items())),
            ("Primary split (chrono, after purge)", ", ".join(f"{p} {n(t.loc[p, 'total'])}" for p in t.index))]
