"""Render the root README.md from committed, machine-readable artifacts (no number is typed by hand).

Numbers come from dashboard.data (the tested accessors over configs/*.json and reports/generated/*), so the README
cannot drift from the frozen results. tests/test_readme.py fails if README.md differs from this script's output.
Usage: .venv/bin/python scripts/render_readme.py
"""
import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path[:0] = [str(ROOT), str(ROOT / "src")]
from dashboard import data as D  # noqa: E402

pct, num = D.pct, D.num


def f5(x):
    return f"{x:.5f}"


def render():
    o, h, fs, g = D.dataset_overview(), D.headline(), D.fp_story(), D.shap_global()
    nov, nov_rows = D.novel_overview()
    comp, cmp_ = D.novel_composition(), D.model_comparison()
    small, ex = D.small_support_labels(), D.model_export()
    prov = json.loads((ROOT / "data/DATASET_PROVENANCE.json").read_text())
    n_pages = len(re.findall(r"st\.Page\(", (ROOT / "dashboard/app.py").read_text()))
    by = fs["by_daygroup"]
    rev, other, val_other = fs["rev"], fs["other"], fs["val_other"]
    imp = g["importance"]
    top5 = ", ".join(f"`{f}`" for f in imp.feature[:5])
    rst = imp.iloc[0]
    grp = g["groups"]
    rf = g["rf"].loc["all_sample"]
    nv = nov_rows[(nov_rows.model == h["family"]) & (nov_rows.subset == "novel_test")].iloc[0]
    scans = comp[comp.label.isin(["Portscan", "Infiltration - Portscan"])]
    budget = pct(h["budget"], 1)
    dec = D.read_csv("m5_shift_decomposition")
    val_rev_thu_fri = int(dec[(dec.partition == "val") & dec.daygroup.isin(["thursday", "friday"])
                              & dec.reverse_of_attack].benign.sum())
    assert all(v for v in ex["verification"].values() if isinstance(v, bool)), "export audit record has a failed check"

    chrono = cmp_[cmp_.protocol.str.startswith("chronological")].set_index("model")
    rnd = cmp_[cmp_.protocol.str.startswith("random")].set_index("model")
    model_rows = "\n".join(
        f"| {m}{' (selected)' if r.selected else ''} | {f5(r.precision)} | {f5(r.recall)} | {f5(r.f1)} | "
        f"{pct(r.fpr, 3)} | {num(r.fp)} | {num(r.fn)} | {f5(r.pr_auc)} |" for m, r in chrono.iterrows())
    split_rows = "\n".join(
        f"| {m} | {pct(chrono.loc[m].fpr, 3)} ({num(chrono.loc[m].fp)} FP) | {pct(rnd.loc[m].fpr, 3)} "
        f"({num(rnd.loc[m].fp)} FP) | {pct(chrono.loc[m].val_fpr, 3)} |" for m in chrono.index)
    day_rows = "\n".join(f"| {d.capitalize() if d != 'mon-wed' else 'Monday–Wednesday'} | {num(r.benign_test)} | "
                         f"{num(r.fp)} | {pct(r.fpr, 3)} |" for d, r in by.iterrows())
    small_txt = ", ".join(f"{l} ({int(n)})" for l, n in zip(small.label, small.n))
    shot = lambda f, alt: f'<img src="reports/figures/m6/{f}" alt="{alt}" width="420">'  # noqa: E731

    return f"""# Explainable Machine-Learning Intrusion Detection under Leakage-Aware Evaluation

![Python 3.12](https://img.shields.io/badge/python-3.12-blue) ![Streamlit dashboard](https://img.shields.io/badge/dashboard-Streamlit-red)

A study of supervised flow-based intrusion detection on the improved CIC-IDS2017 dataset. It uses a leakage-aware chronological evaluation, per-attack-family analysis, SHAP explanations of the frozen model and a read-only research dashboard.

> This is a benchmark study on a 2017 lab dataset. It is not a production intrusion-detection system, it does not monitor live traffic, and its results do not show how a detector would behave on another network.

<!-- Generated by scripts/render_readme.py from configs/*.json and reports/generated/*. Do not edit by hand. -->

## Why this project

Intrusion-detection results on public benchmarks are often reported under random train/test splits. In flow datasets, those splits can put near-identical flows from the same attack burst into both training and test, which makes results look better than they are. In security, the false-positive rate matters as much as detection: an alert rate that looks small on benign traffic is still a large number of alerts. This project asks how a standard detector performs when the evaluation is designed to limit temporal, duplicate and identifier leakage, and what the model's decisions rest on. The conclusions apply to this dataset and protocol only.

## Key findings

All values are from the single frozen test evaluation (protocol v1, {h['family']} selected on validation, threshold fixed on validation for a {budget} false-positive-rate target).

1. **High attack recall on the chronological test set.** The selected {h['family']} model detected {num(h['tp'])} of {num(h['attack'])} test attack flows (recall {f5(h['recall'])}, {num(h['fn'])} missed).
2. **The validation false-positive target did not hold on test.** Validation FPR at the frozen threshold was {pct(h['val_fpr'], 3)}; test FPR was {pct(h['fpr'], 3)} ({num(h['fp'])} false positives on {num(h['benign'])} benign test flows).
3. **The chronological split gave a much higher FPR than a random split.** With the same features, hyper-parameters and threshold rule, the random-split {h['family']} model had a test FPR of {pct(rnd.loc[h['family']].fpr, 3)} ({num(rnd.loc[h['family']].fp)} false positives). The same direction holds for all three model families ([below](#chronological-vs-random-split)).
4. **Most test false positives are reverse-direction traffic from attack scenarios.** {num(rev['fp'])} of {num(h['fp'])} false positives ({pct(rev['fp'] / h['fp'], 1)}) are flows whose source and destination are the reverse of a same-day attack pair. These make up {pct(rev['benign'] / (rev['benign'] + other['benign']), 2)} of benign test flows, and {pct(rev['fpr'], 1)} of them were flagged.
5. **The remaining benign traffic stays close to the intended budget.** Excluding those flows, benign FPR was {pct(other['fpr'], 3)} on test against {pct(val_other['fpr'], 3)} on validation.
6. **The model leans heavily on a few flow-level features.** `{rst.feature}` carries {pct(rst.share_all, 1)} of the total mean absolute SHAP value over the test set. The top five are {top5}. A Random Forest trained on the same data ranks features differently (top-10 overlap {rf.top10_overlap:.1f}).
7. **Novel-vector performance stays high, but that subset has a different attack mix.** On the {num(nov['novel_test'])} test rows whose feature vector never appears in training, recall is {f5(nv.recall)} and FPR {pct(nv.fpr, 3)}. Scans make up {pct(scans.share_of_attacks_full.sum(), 1)} of attack rows in the full test set but only {pct(scans.share_of_attacks_novel.sum(), 1)} in the novel subset, so the two numbers are not directly comparable.

## Pipeline

```mermaid
flowchart LR
    A["Improved CIC-IDS2017<br/>(5 daily CSV files)"] --> B["Data audit<br/>and cleaning"]
    B --> C["Leakage audit<br/>and feature policy"]
    C --> D["Chronological split per<br/>(day, label) stratum<br/>+ boundary purging"]
    D --> E["Preprocessing<br/>fitted on train only"]
    E --> F1["Logistic Regression"]
    E --> F2["Random Forest"]
    E --> F3["LightGBM"]
    F1 & F2 & F3 --> G["Validation-only selection<br/>and threshold freeze"]
    G --> H["Single frozen<br/>test evaluation"]
    H --> I["Novel-vector and<br/>random-split comparison"]
    H --> J["SHAP and<br/>error analysis"]
    I & J --> K["Read-only Streamlit<br/>research dashboard"]
```

## Evaluation methodology

| Step | What was done | Details |
|---|---|---|
| Dataset | {o['dataset']}; {num(o['rows_raw'])} flows, 5 days | [`DATA_CARD.md`](DATA_CARD.md) |
| Data audit | Schema, labels, timestamps, duplicates, non-finite values; {num(o['rows_removed'])} rows with infinite rates removed, leaving {num(o['rows_clean'])} | [`reports/DATA_AUDIT.md`](reports/DATA_AUDIT.md) |
| Leakage audit | Identifier, temporal, duplicate and shortcut-feature risks measured before any model was trained | [`reports/LEAKAGE_AUDIT.md`](reports/LEAKAGE_AUDIT.md) |
| Feature policy | IPs, ports, timestamps, flow IDs and label-derived columns are never model inputs; frozen manifest | [`configs/feature_manifest_v1.json`](configs/feature_manifest_v1.json) |
| Split | Chronological within each (day, original label) stratum: train {num(o['n_train'])}, validation {num(o['n_val'])}, test {num(o['n_test'])} | [`reports/EXPERIMENT_PROTOCOL.md`](reports/EXPERIMENT_PROTOCOL.md) |
| Purging | {num(o['n_purged'])} train/validation rows whose flow interval reaches into the next partition removed; test rows are never removed | same |
| Tuning | Hyper-parameters, model selection, early stopping and thresholds use validation data only; the selection rule was written before training | [`configs/model_selection_v1.json`](configs/model_selection_v1.json) |
| Threshold | Frozen per model on validation for {budget} and 1 % FPR targets | [`configs/m4_frozen.json`](configs/m4_frozen.json) |
| Test-once | The test partition was evaluated once; model files are hash-checked before evaluation | [`reports/MODEL_EVALUATION.md`](reports/MODEL_EVALUATION.md) |
| Novel-vector subset | Test rows whose exact feature vector does not occur in training | protocol §7 |
| Random-split comparison | Same stratum sizes, features and hyper-parameters, random assignment | model evaluation §12 |
| Per-family evaluation | Binary-detector recall per original attack label with Wilson intervals | model evaluation §11 |

**The split is retrospective and label-aware.** Split points are placed inside each (day, label) stratum, which requires the labels. This controls temporal and duplicate leakage within the benchmark. It is not a deployment-style time split, and all attack types are present in training.

## Model comparison

Chronological test partition, {budget} FPR operating point (thresholds chosen on validation):

| Model | Precision | Recall | F1 | FPR | FP | FN | PR-AUC |
|---|---|---|---|---|---|---|---|
{model_rows}

Validation could not separate the two tree models; LightGBM was selected by the predeclared PR-AUC tie-break. Logistic Regression misses most flows of several attack labels. Per-label results are in [`reports/MODEL_EVALUATION.md`](reports/MODEL_EVALUATION.md) §11.

## Chronological vs random split

Test FPR at each model's frozen {budget}-target threshold:

| Model | Chronological split | Random split | Validation FPR (chronological) |
|---|---|---|---|
{split_rows}

In this dataset, the random split produced much lower measured false-positive rates for every model family. The random split puts flows from the same attack windows into both training and test. It is the more optimistic protocol here, and its numbers should not be read as deployment performance. This result is specific to this benchmark and protocol.

## Explainability and false-positive analysis

TreeSHAP was computed for every one of the {num(g['n_test'])} test rows (LightGBM, log-odds output; additivity verified on all rows).

- **Global drivers.** `{rst.feature}` alone carries {pct(rst.share_all, 1)} of mean |SHAP|. By feature group: TCP flags {pct(grp['flags'], 1)}, timing {pct(grp['timing'], 1)}, response sizes {pct(grp['bwd_size'], 1)}, TCP window {pct(grp['tcp_window'], 1)}. Several influential features, such as the victim's initial TCP window, plausibly describe the lab's servers and tools rather than attack behaviour. This is a hypothesis, not an established fact.
- **Where the false positives are.** They concentrate on two days:

| Test day group | Benign flows | False positives | FPR |
|---|---|---|---|
{day_rows}

- **Reverse-direction cluster.** On Thursday and Friday, most false positives are short, reset-terminated flows going *from* hosts that were scanned or attacked *to* the attacker. The model scores them the way it scores scan traffic. The dataset's labelling rules match the attacker as source, so these flows are labelled benign. The per-stratum split puts most of them in the test window: validation has only {num(val_rev_thu_fri)} such benign rows on Thursday and Friday, and training on Thursday and Friday has almost none.
- **What is not claimed.** These rows are "false positives under the benchmark labels". The analysis does not claim that they are mislabelled, and no label was changed (protocol v1). Why only about half of the Friday reverse flows are flagged is unresolved. Whether the pattern holds for other fits of the same model was not tested.
- **Model disagreement.** A Random Forest on the same data attributes differently (top-10 overlap {rf.top10_overlap:.1f}, rank Spearman {rf.spearman:.2f}). SHAP describes one fitted model; it is not a causal account of network attacks.

<img src="reports/figures/m5/fpr_by_direction_val_test.png" alt="Benign FPR by traffic direction, validation vs test" width="720">

Full analysis: [`reports/EXPLAINABILITY_ANALYSIS.md`](reports/EXPLAINABILITY_ANALYSIS.md) (§8–9 false positives, §17 validation→test shift) and [`MODEL_CARD.md`](MODEL_CARD.md).

## Research dashboard

A read-only Streamlit app with {n_pages} pages. It shows the frozen results, per-family recall, SHAP explanations, the false-positive case study, the novel-vector analysis and a case explorer. It is a benchmark and research interface: it does not capture, scan or generate traffic, and it is not a monitoring tool. Every displayed value is read from committed artifacts, and a test fails if a number is typed into a page.

```bash
.venv/bin/python -m streamlit run dashboard/app.py
```

| | |
|---|---|
| {shot('dashboard_overview.png', 'Dashboard overview page')} | {shot('dashboard_evaluation.png', 'Model comparison and chronological vs random split')} |
| Overview | Evaluation: model comparison, chronological vs random split |
| {shot('dashboard_false_positives.png', 'False-positive case study page')} | {shot('dashboard_prediction_demo.png', 'Benchmark case explorer page')} |
| False-positive case study | Benchmark case explorer |

### Benchmark case explorer and the committed model export

The case explorer shows stored test rows with the frozen score and SHAP explanation. It can also recompute both live from [`{ex['export_path']}`]({ex['export_path']}), a {num(ex['export_bytes'])}-byte LightGBM text export of the frozen selected model. This file was not retrained and is not a new model:

- it is a deterministic export of the frozen model file recorded in [`configs/m4_frozen.json`](configs/m4_frozen.json) (unchanged);
- its SHA-256 (`{ex['export_sha256'][:16]}…`) is recorded in [`configs/m6_model_export.json`](configs/m6_model_export.json), and the dashboard loads it only if the hash matches;
- its scores are bit-identical to the frozen model on all {num(ex['verification']['test_rows'])} test rows, and its SHAP values are bit-identical on all {num(ex['verification']['demo_cases'])} explorer cases.

Without the export, the explorer falls back to the stored scores and SHAP values. See [`dashboard/README.md`](dashboard/README.md).

## Repository structure

```
├── README.md, PROJECT_PLAN.md, DATA_CARD.md, MODEL_CARD.md
├── configs/          frozen protocol-v1 configs, model-selection rule, frozen model record, export record
├── src/ids/          data loading, preparation/splitting, preprocessing, modelling, metrics, SHAP helpers
├── scripts/          pipeline entry points (audit → prepare → train/evaluate → explain → render) and git hook
├── reports/          audit, protocol, evaluation and explainability reports
│   ├── generated/    machine-readable tables behind every reported number
│   └── figures/      SHAP/error-analysis figures (m5) and dashboard screenshots (m6)
├── dashboard/        Streamlit app, data layer and the frozen-model text export
├── data/             download instructions and provenance record (the data itself is not committed)
└── tests/            unit, consistency and dashboard tests
```

## Installation

Requires Python 3.12 and [uv](https://docs.astral.sh/uv/). Direct dependencies are pinned in [`requirements.txt`](requirements.txt).

```bash
git clone https://github.com/Vanshcloud/Intrusion-Detection-System.git
cd Intrusion-Detection-System
uv venv --python 3.12 .venv
uv pip install --python .venv -r requirements.txt
.venv/bin/python -m pytest                          # tests needing the dataset or local artifacts are skipped
.venv/bin/python -m streamlit run dashboard/app.py  # opens the dashboard on http://localhost:8501
```

## Dataset setup

The dataset is **not** included in this repository and is not redistributed.

- **Version used:** {o['dataset']}. It is re-extracted from the original CIC-IDS2017 packet captures with corrected flow extraction and labelling.
- **Source:** <{prov['source_url']}> (documentation: <{prov['documentation_urls'][0]}>). Original dataset: <https://www.unb.ca/cic/datasets/ids-2017.html>.
- **Expected location:** `data/raw/{prov['archive_filename']}`, extracted to `data/raw/CICIDS2017_improved/*.csv` by `scripts/provenance.py`. The SHA-256 of the archive used here is recorded in [`data/DATASET_PROVENANCE.json`](data/DATASET_PROVENANCE.json). The upstream authors publish no checksum.
- **Licence:** no licence text was found for the improved dataset. The CIC page describes CIC-IDS2017 as available to researchers and asks users to cite the original paper. The licensing terms for redistribution are unclear, which is why no data is committed. Cite the dataset papers ([references](#references)).

Download, audit and preparation commands are in [`data/README.md`](data/README.md).

## Reproducing the research

| Level | Needs | What it reproduces | How |
|---|---|---|---|
| 1. Reports and dashboard | a normal clone | every report, table, figure and dashboard page; model-export hash check; README regeneration | install as above; `.venv/bin/python scripts/render_readme.py` |
| 2. Data preparation | clone + raw dataset | audit tables, cleaning, splits, novel-vector flags (`data/interim/`, `data/processed/`) | [`data/README.md`](data/README.md) |
| 3. Model training and test evaluation | level 2 | the grid search, frozen models and single test evaluation (`artifacts/m4/`) | [`reports/MODEL_EVALUATION.md`](reports/MODEL_EVALUATION.md) §17 |
| 4. Full SHAP analysis | level 3 | the SHAP census over all test and validation rows (`artifacts/m5/`, several hundred MB) and the M5 tables and figures | [`reports/EXPLAINABILITY_ANALYSIS.md`](reports/EXPLAINABILITY_ANALYSIS.md) §22 |

`data/raw/`, `data/interim/`, `data/processed/` and `artifacts/` are intentionally not tracked (see [`.gitignore`](.gitignore)). They are large and can be regenerated. The only model file in the repository is the compact text export described above. Levels 2–4 were run when each milestone was produced, and the stored predictions and SHAP outputs were verified to reproduce (hashes and checks in `configs/` and `reports/generated/`). Re-running levels 3–4 rewrites the frozen records, so compare the results with the committed versions using `git diff`. With the local artifacts present, `.venv/bin/python scripts/m6_export_model.py --check` re-verifies the model export against the frozen model.

## Limitations

- **Benchmark, not deployment.** All traffic comes from one 2017 lab testbed. Training, validation and test share the same attack environment, tools, hosts and scripted runs.
- **High near-duplicate overlap.** {pct(nov['attack_near_overlap_share'], 1)} of attack test rows have a near-identical (non-timing) feature vector in training, and {pct(nov['attack_exact_overlap_share'], 1)} have an exact match.
- **Label-aware split.** The chronological cut is made per (day, label) stratum. It is retrospective and would not be available in deployment.
- **Small classes.** Some attack labels have too few test rows for stable estimates: {small_txt}.
- **Scenario-dependent false positives.** The test FPR depends heavily on which attack scenarios fall in the test window.
- **Reused validation data.** Validation data was used for early stopping, model selection and threshold choice, so validation metrics are optimistic.
- **No independent network.** The detector was not evaluated on a different dataset or network. Cross-environment generalisation is unknown.
- **Single fit.** One seed and one fitted model per family, so refit variability was not measured.
- **SHAP is not causal.** Attributions describe the frozen model and differ between model families.
- **Not a production IDS.** No streaming, no deployment engineering and no adversarial robustness evaluation.

## Responsible use

This repository is for defensive research and benchmark analysis. It contains no offensive tooling, traffic generation, scanning or exploitation code. The dataset's attack traffic was produced by its original authors in a lab. The model and dashboard should not be used to make security decisions about real networks.

## License

- **Source code** in this repository (Python modules, scripts, tests, dashboard and configuration) is released under the [MIT License](LICENSE), copyright (c) 2026 Vansh Tomar.
- **CIC-IDS2017 dataset:** not distributed in this repository and **not** covered by the MIT License. Obtain it separately from its provider; it is subject to the provider's own terms and conditions, and the dataset authors ask users to cite their papers (see [Dataset setup](#dataset-setup) and [References](#references)).
- **Dataset-derived files:** the generated tables in `reports/generated/` (aggregate statistics and {num(ex['verification']['demo_cases'])} example test rows used by the case explorer), the figures and the model export were produced from the dataset. The MIT License covers the code and the analysis write-up, but it does not grant rights in the underlying dataset content.

## References

1. I. Sharafaldin, A. H. Lashkari, A. A. Ghorbani. "Toward Generating a New Intrusion Detection Dataset and Intrusion Traffic Characterization." *Proc. ICISSP*, 2018, pp. 108–116. [doi:10.5220/0006639801080116](https://doi.org/10.5220/0006639801080116)
2. G. Engelen, V. Rimmer, W. Joosen. "Troubleshooting an Intrusion Detection Dataset: the CICIDS2017 Case Study." *IEEE Security and Privacy Workshops (SPW)*, 2021, pp. 7–12. [doi:10.1109/SPW53761.2021.00009](https://doi.org/10.1109/SPW53761.2021.00009)
3. L. Liu, G. Engelen, T. Lynar, D. Essam, W. Joosen. "Error Prevalence in NIDS datasets: A Case Study on CIC-IDS-2017 and CSE-CIC-IDS-2018." *IEEE Conference on Communications and Network Security (CNS)*, 2022, pp. 254–262. [doi:10.1109/CNS56114.2022.9947235](https://doi.org/10.1109/CNS56114.2022.9947235)
4. M. Lanvin, P.-F. Gimenez, Y. Han, F. Majorczyk, L. Mé, É. Totel. "Errors in the CICIDS2017 Dataset and the Significant Differences in Detection Performances It Makes." *CRiSIS 2022*, LNCS, Springer, 2023, pp. 18–33. [doi:10.1007/978-3-031-31108-6_2](https://doi.org/10.1007/978-3-031-31108-6_2)
5. D. Arp et al. "Dos and Don'ts of Machine Learning in Computer Security." *31st USENIX Security Symposium*, 2022. <https://www.usenix.org/conference/usenixsecurity22/presentation/arp>
6. S. M. Lundberg, S.-I. Lee. "A Unified Approach to Interpreting Model Predictions." *NIPS 30*, 2017.
7. S. M. Lundberg et al. "From local explanations to global understanding with explainable AI for trees." *Nature Machine Intelligence* 2, 56–67, 2020. [doi:10.1038/s42256-019-0138-9](https://doi.org/10.1038/s42256-019-0138-9)
"""


def main():
    (ROOT / "README.md").write_text(render())
    print("wrote README.md")


if __name__ == "__main__":
    main()
