"""Render reports/EXPLAINABILITY_ANALYSIS.md and MODEL_CARD.md from Milestone 5 outputs (numbers only from files).

Inputs: reports/generated/m5_*.csv, m5_facts.json, m5_reproducibility.json (scripts/m5_analyze.py,
scripts/m5_explain.py --verify), artifacts/m5/run.json, and the Milestone 4 tables for the model card.
"""
import json
import sys
from pathlib import Path

import pandas as pd

sys.path.insert(0, str(Path(__file__).resolve().parents[1] / "src"))
sys.path.insert(0, str(Path(__file__).resolve().parent))
from ids.data import GENERATED, ROOT  # noqa: E402
from render_m4 import md  # noqa: E402

F = json.loads((GENERATED / "m5_facts.json").read_text())
RUN = json.loads((ROOT / "artifacts/m5/run.json").read_text())
REP = json.loads((GENERATED / "m5_reproducibility.json").read_text()) if (GENERATED / "m5_reproducibility.json").exists() else None
FIGDIR = "figures/m5"


def T(name, **kw):
    return pd.read_csv(GENERATED / f"m5_{name}.csv", **kw)


def pct(x, d=2):
    return f"{100 * x:.{d}f} %"


def ci_txt(r, d=3):
    return f"{100 * r.fpr:.{d}f} % (95 % CI {100 * r.ci95_low:.{d}f}–{100 * r.ci95_high:.{d}f} %)"


def fig(name, alt):
    return f"![{alt}]({FIGDIR}/{name})\n"


def main():
    P = RUN["provenance"]
    sel = P["models"]["E1_primary__lgbm"]
    o = F["outcomes"]
    g = T("global_importance")
    gp = T("group_share_by_population").set_index("population")
    byday = T("fp_by_day")
    cmp_ = T("fp_daygroup_compare").set_index("daygroup")
    fpf = T("fp_top_features_by_daygroup")
    hp = T("fp_host_pairs")
    prof = T("fp_profile").set_index("daygroup")
    dec = T("shift_decomposition")
    sq = T("shift_score_quantiles")
    ks = T("feature_shift_val_test")
    fn = T("fn_cases")
    fam = T("family_top_features")
    famg = T("family_group_share")
    famov = T("family_top10_overlap", index_col=0)
    rare = T("rare_family_cases")
    nov = T("novel_vs_full")
    dup = T("dup_vs_novel_by_label")
    e12 = T("e1_vs_e2_summary")
    rfs = T("lgbm_vs_rf_summary")
    rfg = T("lgbm_vs_rf_groups", index_col=0)
    st = T("stability_bootstrap")
    ps = T("stability_population_top10_overlap", index_col=0)
    inter = T("interactions_top")
    sqo = T("score_quantiles")
    cb = T("casebook")

    def D(part, dg, rv):
        return dec[(dec.partition == part) & (dec.daygroup == dg) & (dec.reverse_of_attack == rv)].iloc[0]
    tr_all, tr_other, va_other, va_rev = D("test", "all", True), D("test", "all", False), D("val", "all", False), D("val", "all", True)
    ben_test = int(tr_all.benign + tr_other.benign)
    ben_val = int(va_rev.benign + va_other.benign)
    top5 = ", ".join(f"`{f}`" for f in g.feature[:5])
    thu, fri, mw = cmp_.loc["thursday"], cmp_.loc["friday"], cmp_.loc["mon-wed"]
    s_rst = g.set_index("feature").loc["RST Flag Count"]
    dep = F["dep"]
    fz = json.loads((ROOT / "configs/m4_frozen.json").read_text())
    BEST_IT = next(x for x in fz["experiments"] if x["run_id"] == fz["overall_selected"])["best_iteration"]

    def V(dg, feat, who="fp"):
        r = fpf[(fpf.daygroup == dg) & (fpf.feature == feat)].iloc[0]
        return f"{r[f'{who}_median_value']:.6g}"

    out = []
    w = out.append
    w("# Explainability Analysis — Milestone 5 (SHAP, false-positive and error analysis)\n")
    w("Generated by `scripts/render_m5.py` from `reports/generated/m5_*` (produced by `scripts/m5_explain.py` and "
      "`scripts/m5_analyze.py`). No number in this file is typed by hand. **Observed** marks what the artifacts show; "
      "**Interpretation** / **Hypothesis** marks explanations of it. SHAP values describe how the frozen model's output "
      "depends on its inputs; they are not causal effects in the network, and a feature with large SHAP values "
      "*contributes strongly to the model's predictions* — it does not cause attacks. Metadata (IPs, ports, times) is used "
      "only to describe rows; it is never a model input.\n")

    w("## 1. Objective\n")
    w("Explain the frozen protocol-v1 detector from Milestone 4 — what it relies on, why its false positives concentrate on "
      "Thursday and Friday, what its few misses look like, and how far the explanations can be trusted. Nothing was "
      "retrained, re-tuned, re-thresholded or relabelled; no SHAP result was used to change the model.\n")

    w("## 2. Frozen model and protocol\n")
    w(md(pd.DataFrame([
        ("Selected model", f"`{sel['path']}`"), ("Model SHA-256", f"`{sel['sha256']}`"),
        ("Frozen threshold (0.1 % validation FPR target)", f"{sel['threshold_0.001']:.6f}"),
        ("Model inputs", f"{F['n_model_inputs']} (82 manifest features; `Bwd URG Flags` removed as constant in train by the frozen preprocessor)"),
        ("Preprocessor", P["preprocessor"]),
        ("`configs/m4_frozen.json` SHA-256", f"`{P['m4_frozen_sha256']}`"),
        ("`configs/experiment_protocol_v1.json` SHA-256", f"`{P['protocol_sha256']}`"),
        ("Secondary models", "E1 Random Forest (`" + P["models"]["E1_primary__rf"]["path"] + "`), E2 random-split LightGBM (`"
         + P["models"]["E2_random__lgbm"]["path"] + "`)"),
        ("Test outcomes at the frozen threshold", f"TP {o['TP']:,} · FP {o['FP']:,} · TN {o['TN']:,} · FN {o['FN']:,} (identical to Milestone 4)"),
    ], columns=["Item", "Value"])))
    w("\nEvery model file hash was checked before use; the attack scores recomputed from each frozen model equal the "
      "stored Milestone 4 predictions exactly (E1 test, E1 validation, E2 test: "
      f"{', '.join(k for k, v in RUN['checks'].items() if k.endswith('equal_stored') and v)}). "
      "Logistic regression was not explained with SHAP (not required; its coefficients act on log-scaled, standardised "
      "inputs and add little to the tree-model questions here).\n")

    w("## 3. SHAP methodology\n")
    w(f"- Library versions: shap {P['shap']}, LightGBM {P['lightgbm']}, scikit-learn {P['sklearn']}, Python {P['python']}.\n"
      "- Method: path-dependent TreeSHAP (tree cover statistics from training; no background sample). For LightGBM the "
      "native `pred_contrib` implementation is used; on the uniform sample it equals `shap.TreeExplainer` with maximum "
      f"absolute difference {RUN['checks']['shap_library_vs_native_max_abs_diff']:g}.\n"
      f"- **Output space (verified, not assumed): LightGBM SHAP values are in raw margin = log-odds of attack.** "
      f"Base value {F['base_log_odds']:.4f} (probability {F['base_probability']:.4f}); sigmoid(base + Σ SHAP) reproduces "
      f"the stored attack probability on all {F['n_test']:,} test rows with maximum absolute error "
      f"{F['stored_additivity_max_abs_prob_error']:.1e}. The booster holds {F['booster_trees']} trees and "
      f"`best_iteration_` = {F['best_iteration']} (frozen config: {BEST_IT}), so SHAP covers exactly the trees used for prediction.\n"
      f"- Random Forest SHAP values are in **probability of attack** (base {RUN['E1_rf']['base']:.4f}); additivity is "
      "checked against `predict_proba` on every explained row. LightGBM and RF values are therefore compared by rank and "
      "normalised share, never by raw magnitude.\n"
      "- Feature order: SHAP columns are the frozen preprocessor's output names; the LightGBM booster's feature names are "
      "checked against them before every call (`src/ids/explain.py`).\n"
      f"- Repeatability: reloading the model from disk reproduces the SHAP matrix bitwise "
      f"({RUN['checks']['reload_bitwise_identical']}). SHAP interaction values sum back to the SHAP values within "
      f"{RUN['checks']['interaction_rows_sum_to_shap_max_abs_diff']:.1e}.\n")

    w("## 4. Explanation sample design\n")
    w(f"Computing TreeSHAP for every test row was benchmarked as feasible (selected LightGBM: {F['timing_s']['E1_lgbm_test']} s "
      f"for {F['n_test']:,} rows), so **LightGBM explanations are a census, not a sample**. Three populations are kept "
      "separate and labelled wherever used:\n")
    w(md(pd.DataFrame([
        ("Census (test)", f"{F['n_test']:,}", "every chronological-test row; natural composition", "global/per-family/FP/FN/novelty tables"),
        ("Census (validation)", f"{F['n_val']:,}", "every validation row", "validation→test shift (§17)"),
        ("Uniform sample", f"{F['n_uniform']:,}", "uniform without replacement from key-sorted test rows, seed "
         f"{RUN['seed']}", "beeswarm, dependence plots, interaction values (first 1,000 rows), directionality"),
        ("Stratified sample", f"{F['rf_sample_n']:,}", "all FP ({FP}) and FN ({FN}); TN capped at 150 per (day, novel); TP capped at 150 per "
         "(label, novel); seeded, key-sorted".format(**F["stratified_group_counts"]),
         "Random Forest SHAP, LightGBM-vs-RF comparison, casebook"),
    ], columns=["Population", "Rows", "Rule", "Used for"])))
    w("\nThe stratified sample over-represents errors and rare labels by design; it is never used for a pooled "
      "\"global importance\" claim. Row IDs (`source_file`, `source_row`) of both samples are stored in "
      "`artifacts/m5/sample_*.parquet` and are re-derived identically by a clean rerun (§22).\n")

    w("## 5. Global feature importance (census, full chronological test)\n")
    w(fig("global_importance.png", "Global mean |SHAP|"))
    gg = g.head(15)[["rank", "feature", "group", "mean_abs_all", "share_all", "mean_abs_benign", "mean_abs_attack",
                     "spearman_value_vs_shap_uniform", "direction"]]
    w(md(gg, 3))
    w(f"\n**Observed:** `RST Flag Count` alone carries {pct(s_rst.share_all, 1)} of total mean |SHAP| over the test set; the "
      f"top five features ({top5}) carry {pct(g.share_all[:5].sum(), 1)}. By feature group (census): flags "
      f"{pct(gp.loc['all_test', 'flags'], 1)}, timing {pct(gp.loc['all_test', 'timing'], 1)}, backward (response) sizes "
      f"{pct(gp.loc['all_test', 'bwd_size'], 1)}, TCP window {pct(gp.loc['all_test', 'tcp_window'], 1)}, header length "
      f"{pct(gp.loc['all_test', 'header_length'], 1)}, protocol {pct(gp.loc['all_test', 'protocol'], 2)}. `Dst Port` is not an "
      "input of the frozen model. `direction` is the Spearman correlation between a feature's value and its SHAP value on "
      "the uniform sample (|ρ| ≥ 0.5 reported as monotone); most features are non-monotone.\n")
    w(fig("beeswarm_uniform.png", "SHAP beeswarm"))
    w("**Interpretation:** the model's output is dominated by TCP flag counts and flow duration — properties of how a TCP "
      "exchange ends (reset vs orderly close) rather than payload content. This is consistent with the Milestone 2 finding "
      "that almost every attack is separable by one or two flow statistics in this testbed. It is a description of the "
      "model, not evidence that RST packets are malicious.\n")

    w("## 6. Per-family patterns (test attack rows, labels with n ≥ 30)\n")
    w(fig("family_group_share.png", "Per-family feature-group shares"))
    t = fam[fam["rank"] <= 5].copy()
    t["feature (share, mean signed SHAP)"] = t.feature + " (" + t.share.map("{:.2f}".format) + ", " + t.mean_signed.map("{:+.2f}".format) + ")"
    w(md(t.groupby(["label", "n"])["feature (share, mean signed SHAP)"].agg(" · ".join).reset_index()))
    top1 = fam[fam["rank"] == 1].set_index("label").feature
    exc = top1[top1 != "RST Flag Count"]
    off = famov.where(~pd.DataFrame([[a == b for b in famov.columns] for a in famov.index], index=famov.index, columns=famov.columns))
    w(f"\n**Observed:** `RST Flag Count` is the top feature for {int((fam[fam['rank'] == 1].feature == 'RST Flag Count').sum())} of "
      f"{fam.label.nunique()} families; the exceptions are " + ", ".join(f"{l} (`{f}`)" for l, f in exc.items()) + ". Pairwise top-10 "
      f"overlap between families ranges {off.min().min():.1f}–{off.max().max():.1f} (median {pd.Series(off.values.ravel()).median():.1f}; "
      f"`m5_family_top10_overlap.csv`); the least similar family on average is {off.mean().idxmin()} (mean overlap "
      f"{off.mean().min():.2f}). Full per-family tables: "
      "`m5_family_top_features.csv` (mean |SHAP|, mean signed SHAP, SD, median value).\n")
    w("**Interpretation:** families share a common core (flags, response size, backward window) with family-specific "
      "secondary features. Several of these — the victim's initial TCP window (`Bwd Init Win Bytes`), response-size "
      "statistics — describe the *victim server's* reply in this lab rather than attacker behaviour; this supports the "
      "Milestone 2 concern that detection partly rests on victim/tool signatures. SHAP cannot show whether the model "
      "\"understands\" an attack.\n")

    w("## 7. True-positive explanations\n")
    tp_sc = sqo[(sqo.set == "test outcome") & (sqo.group == "TP")].iloc[0]
    w(f"**Observed:** true positives (n = {o['TP']:,}) have median score {tp_sc['q0.5']:.4f} and 1 % quantile "
      f"{tp_sc['q0.01']:.4f} (`m5_score_quantiles.csv`); their mean total |SHAP| is "
      f"{nov.set_index('population').loc['full_test', 'mean_sum_abs_shap']:.2f} log-odds over all rows and much larger for "
      "attacks than for benign rows (`m5_global_importance.csv`, `mean_abs_attack` vs `mean_abs_benign`). The large DoS/DDoS "
      "and scan families are carried by `RST Flag Count` together with `Bwd Packet Length Std` (DoS/DDoS) or `Flow Duration` "
      "(scans); see §6. Representative local explanations are in the casebook (§19).\n")

    w("## 8. False-positive analysis\n")
    w(f"Test false positives at the frozen threshold: **{o['FP']:,}** (\"false positives under the benchmark labels\"). "
      f"They fall in {F['fp_n_pairs']} ordered (day, source, destination) host pairs; the 15 largest pairs hold "
      f"{pct(F['fp_top15_pairs_share'], 1)} of them.\n")
    bd = byday.copy()
    bd["fpr (95 % CI)"] = bd.apply(lambda r: ci_txt(r), axis=1)
    w(md(bd[["partition", "day", "benign", "fp", "fpr (95 % CI)", "fp_reverse", "fp_attempted", "benign_reverse_share"]], 5))
    w("\n`fp_reverse` = FPs whose (destination, source) is a successful-attack (source, destination) pair on the same day; "
      "`benign_reverse_share` = share of all benign rows of that day/partition with that property.\n")
    w("Largest false-positive host pairs:\n")
    w(md(hp[["day", "Src IP", "Dst IP", "fp", "benign_test_rows", "fpr_within_pair", "reverse_of_attack", "reverse_attack_labels",
             "train_benign_rows", "val_benign_rows", "val_fp", "top_dst_ports"]], 3))
    w(f"\n**Observed:**\n"
      f"- {int(tr_all.fp):,} of {o['FP']:,} FPs ({pct(tr_all.fp / o['FP'], 1)}) are reverse-direction traffic of a same-day attack pair; "
      f"reverse-direction benign rows make up {pct(tr_all.benign / ben_test, 2)} of test benign rows but have an FPR of {ci_txt(tr_all, 1)}.\n"
      f"- Thursday: FPs run from the internal hosts scanned by `192.168.10.8` (the Infiltration - Portscan source) back to it; the "
      "scanned hosts' ports appear as source ports and ephemeral high ports as destination ports. Friday: "
      "`192.168.10.50 → 172.16.0.1`, the reverse of the Friday DDoS and Portscan pair.\n"
      f"- The reverse-direction pairs in this table have {int(hp[hp.reverse_of_attack].train_benign_rows.max())} benign rows in train and at most "
      f"{int(hp[hp.reverse_of_attack].val_benign_rows.max())} in validation (`train_benign_rows`, `val_benign_rows`).\n"
      f"- Wednesday's FPs are different: `172.16.0.1 → 192.168.10.50` on port 80 in the *attack* direction, "
      f"{int(byday[(byday.partition == 'test') & (byday.day == 'wednesday')].fp_attempted.iloc[0])} of them labelled `- Attempted` "
      "(the Milestone 4 per-label table attributes flagged Attempted rows mainly to `DoS Slowhttptest - Attempted`), benign under the protocol-v1 target.\n"
      f"- FPs collapse onto few model inputs: Thursday {int(prof.loc['thursday', 'fp']):,} FPs have "
      f"{int(prof.loc['thursday', 'distinct_vectors'])} distinct feature vectors and {int(prof.loc['thursday', 'distinct_scores'])} "
      f"distinct scores; Friday {int(prof.loc['friday', 'fp'])} FPs, {int(prof.loc['friday', 'distinct_vectors'])} vectors, "
      f"{int(prof.loc['friday', 'distinct_scores'])} scores (`m5_fp_profile.csv`).\n"
      f"- FPs have {thu.fp_median_sum_abs_shap / thu.tn_median_sum_abs_shap:.1f}× (Thursday) and {fri.fp_median_sum_abs_shap / fri.tn_median_sum_abs_shap:.1f}× (Friday) the median total |SHAP| of same-day true negatives (median Σ|SHAP| Thursday {thu.fp_median_sum_abs_shap:.1f} vs "
      f"{thu.tn_median_sum_abs_shap:.1f} for Thursday TNs): they are confident predictions, not borderline ones "
      f"(median FP score Thursday {thu.fp_score_median:.3f}, Friday {fri.fp_score_median:.3f}; threshold {sel['threshold_0.001']:.4f}).\n"
      f"- {F['fp_novel']:,} of {o['FP']:,} FPs are novel vectors (no exact match in train). Of the Thursday FP vectors, "
      f"{int(prof.loc['thursday', 'in_train_as_benign_only'])} occur in train with a benign label only and none with an attack label.\n")
    w(fig("score_by_outcome.png", "Scores by outcome"))

    w("## 9. Thursday vs Friday vs Monday–Wednesday\n")
    cols = ["benign_test", "fp", "fpr", "ci95_low", "ci95_high", "fp_share_reverse", "fp_share_attempted",
            "fp_share_in_attack_window", "tn_share_in_attack_window", "benign_score_q0.99", "benign_score_q0.999",
            "fp_score_median", "fp_median_sum_abs_shap", "tn_median_sum_abs_shap", "fp_top5_features", "fp_protocols",
            "fp_top_dst_ports", "fp_top_src_ports", "fp_n_host_pairs", "fp_top3_pairs_share", "fp_top_pairs"]
    c = cmp_[cols].T.reset_index().rename(columns={"index": "quantity"})
    for k in DG:
        c[k] = c[k].map(lambda v: f"{v:.5g}" if isinstance(v, float) else v)
    w(md(c))
    w("\n`in_attack_window` = flow start inside [first start, last end] of a same-day successful-attack label; protocol codes: "
      "6 = TCP, 17 = UDP, 1 = ICMP, 0 = the flagged Protocol-0 rows.\n")
    w(fig("fp_features_by_daygroup.png", "FP features by day group"))
    w(md(fpf, 3))
    w(f"\n**Observed:**\n"
      f"- Thursday ({ci_txt(thu, 2)}) and Friday ({ci_txt(fri, 2)}) FPs are carried by the **same features**: "
      f"`RST Flag Count` (FP median value {V('thursday', 'RST Flag Count')} on Thursday, {V('friday', 'RST Flag Count')} on Friday; "
      f"TN median {V('thursday', 'RST Flag Count', 'tn')}), very short `Flow Duration` (FP median {V('thursday', 'Flow Duration')} µs Thursday, "
      f"{V('friday', 'Flow Duration')} µs Friday; TN median {V('thursday', 'Flow Duration', 'tn')} µs), with `Fwd Seg Size Min` "
      f"(FP median {V('thursday', 'Fwd Seg Size Min')}) and `Bwd Init Win Bytes` (FP median {V('thursday', 'Bwd Init Win Bytes')}) "
      "pulling *toward benign* (negative mean signed SHAP). Their group-share profiles are nearly identical "
      f"(flags {pct(gp.loc['FP_thursday', 'flags'], 0)} / {pct(gp.loc['FP_friday', 'flags'], 0)}, timing "
      f"{pct(gp.loc['FP_thursday', 'timing'], 0)} / {pct(gp.loc['FP_friday', 'timing'], 0)}).\n"
      f"- They differ in **host pairs and scenario**: Thursday FPs come from {int(thu.fp_n_host_pairs)} pairs, mostly scanned "
      f"internal hosts replying to `192.168.10.8`; Friday FPs are {pct(fri.fp_top3_pairs_share, 0)} one pair "
      "(`192.168.10.50 → 172.16.0.1`).\n"
      f"- Thursday reverse rows are flagged almost always ({ci_txt(D('test', 'thursday', True), 1)}), Friday reverse rows about "
      f"half the time ({ci_txt(D('test', 'friday', True), 1)}).\n"
      f"- The mean SHAP vector of Thursday FPs is closest to that of Portscan attack rows ({prof.loc['thursday', 'closest_family_profiles']}); "
      f"Friday FPs likewise ({prof.loc['friday', 'closest_family_profiles']}). Monday–Wednesday FPs resemble the DoS profile "
      f"({prof.loc['mon-wed', 'closest_family_profiles']}).\n"
      f"- Monday–Wednesday FPs ({ci_txt(mw, 3)}) are {pct(mw.fp_share_attempted, 0)} `- Attempted` rows and none are reverse-direction.\n")
    w("**Interpretation:** the Thursday/Friday false positives are one phenomenon seen through two scenarios: short, "
      "reset-terminated flows in the reply direction of a scan (Thursday internal scan; Friday external scan/DDoS), which the "
      "model scores the way it scores scan flows. The day difference is driven by *which host pairs and scenario* are "
      "present, not by different features.\n")
    w("**Hypothesis (not established):** these rows are parts of scan exchanges that the flow meter recorded as separate "
      "flows initiated by the victim (e.g. RST/ACK replies that outlived or preceded the original flow record). The improved "
      "dataset's labelling matches the attacker as *source*, so such rows keep `BENIGN` — a possible labelling asymmetry or "
      "scenario artefact. This is not claimed as mislabelling; no row was relabelled (protocol v1).\n")

    w("## 10. False-negative cases (all of them)\n")
    fc = fn.copy()
    fc["id"] = fc.source_file.str.replace(".csv", "", regex=False) + ":" + fc.source_row.astype(str)
    grp = fc.groupby("label").agg(n=("id", "size"), label_test_n=("label_test_n", "first"),
                                  min_margin=("logit_margin", "min"), max_margin=("logit_margin", "max"),
                                  novel=("novel", "sum"), exact_in_train=("exact_vector_in_train_benign", "sum"),
                                  median_outside=("features_outside_train_label_p0.5_p99.5", "median"),
                                  tp_median_outside=("median_same_for_label_TPs", "first"),
                                  train_rows=("train_rows_same_label", "first")).reset_index()
    w(md(grp, 2))
    w(f"\n`logit_margin` = logit(score) − logit(threshold) (negative = below threshold). `median_outside` = features of the FN "
      "outside its label's train [0.5 %, 99.5 %] range, compared with the same count for that label's test TPs. Case table "
      "(all 53 rows, top three contributions toward benign and toward attack): `reports/generated/m5_fn_cases.csv`. Excerpt:\n")
    ex = fc.sort_values("logit_margin", ascending=False).groupby("label").head(1)
    w(md(ex[["id", "label", "score", "logit_margin", "novel", "top_toward_benign", "top_toward_attack"]], 4))
    w(f"\n**Observed:** all {len(fn)} FNs are novel vectors and none has an exact match in train (benign or attack). "
      f"`RST Flag Count = 0` is among the top contributions toward benign in "
      f"{int(fc.top_toward_benign.str.contains('RST Flag Count=0').sum())} of {len(fn)} cases — the misses are attack flows that "
      "*lack* the reset signature the model leans on. SSH-Patator misses sit far outside that label's typical training range "
      f"(median {grp.set_index('label').loc['SSH-Patator', 'median_outside']:.0f} features outside vs "
      f"{grp.set_index('label').loc['SSH-Patator', 'tp_median_outside']:.0f} for its TPs). Margins range from "
      f"{fc.logit_margin.min():.2f} to {fc.logit_margin.max():.2f} log-odds; "
      f"{int((fc.logit_margin > -1).sum())} are within 1 log-odds unit of the threshold.\n")
    w("**Caution:** Infiltration (10 FNs of 11 test rows, 20 training rows) and Heartbleed (1 of 3) have too few rows for "
      "general statements; their `outside` counts use tiny reference sets. These are case descriptions only.\n")

    w("## 11. Novel-vector explanations\n")
    w(md(nov, 3))
    w(f"\n**Observed:** on the novel subset the global ranking is almost unchanged (Spearman "
      f"{nov.set_index('population').loc['novel_test', 'spearman_with_full']:.3f}, top-10 overlap "
      f"{nov.set_index('population').loc['novel_test', 'top10_overlap_with_full']:.1f}); {F['fp_novel']:,} of {o['FP']:,} FPs are "
      f"novel and their explanation profile equals that of all FPs (top-10 overlap {F['fp_novel_vs_full_fp_top10_overlap']:.1f}). "
      "The novel subset has a lower attack share (scans are mostly duplicated), so pooled magnitudes shift with composition.\n")
    w("**Interpretation:** explanations do not change materially when exact-duplicate vectors are removed; the "
      "false-positive mechanism is entirely a novel-vector phenomenon.\n")

    w("## 12. Duplicate vs novel vectors (within label)\n")
    w(md(dup, 3))
    w("\n**Observed:** comparisons are made within label (only labels with ≥ 30 novel and ≥ 30 duplicated rows) to control "
      "for family mix. For the scan labels, novel rows receive lower scores than duplicated ones (mean logit "
      f"{dup.set_index('label').loc['Portscan', 'mean_logit_novel']:.2f} vs {dup.set_index('label').loc['Portscan', 'mean_logit_dup']:.2f} "
      "for Portscan) with partly different top features (top-5 overlap "
      f"{dup.set_index('label').loc['Portscan', 'top5_overlap']:.1f}). For BENIGN rows the score and |SHAP| levels are nearly "
      "equal. **Interpretation:** duplicated scan rows are the most templated vectors and sit deepest in the attack region; "
      "this is an association, not a causal effect of duplication.\n")

    w("## 13. Random-split explanation comparison (E2, frozen)\n")
    w(md(e12, 3))
    w(f"\n**Observed:** the E2 model (same hyper-parameters, trained on the random split) ranks features similarly "
      f"(all-test Spearman {e12.set_index('population').loc['all_test', 'spearman']:.2f}, top-10 overlap "
      f"{e12.set_index('population').loc['all_test', 'top10_overlap']:.1f}) but with larger magnitudes (mean Σ|SHAP| "
      f"{e12.set_index('population').loc['all_test', 'E2_mean_sum_abs']:.1f} vs {e12.set_index('population').loc['all_test', 'E1_mean_sum_abs']:.1f}). "
      f"Its {F['E2_fp']} test FPs are {pct(F['E2_fp_reverse_share'], 0)} reverse-direction; on its own test set, reverse-direction "
      f"benign rows have FPR {pct(F['E2_fpr_reverse'], 2)} (E1: {pct(tr_all.fpr, 1)}) and other benign rows "
      f"{pct(F['E2_fpr_other'], 3)}. Each model is explained on its own test partition (the partitions differ), so this is not "
      "a paired comparison.\n")
    w("**Interpretation:** the evidence does *not* show that the random split makes the model rely on different, more "
      "scenario-specific features. What differs observably is how the two models score reply-direction rows; a plausible "
      "reason is exposure — under the random split such rows from the attack windows are also in training. This is "
      "consistent with the §17 account of the chronological FPR gap.\n")

    w("## 14. LightGBM vs Random Forest\n")
    w(fig("model_comparison_importance.png", "Model comparison"))
    w(md(rfs, 3))
    w("\nFeature-group shares (stratified sample):\n")
    w(md(rfg.reset_index().rename(columns={"index": "group"}), 3))
    w(f"\n**Observed:** the two tree models agree only moderately (top-10 overlap {rfs.set_index('population').loc['all_sample', 'top10_overlap']:.1f}, "
      f"Spearman {rfs.set_index('population').loc['all_sample', 'spearman']:.2f}, median per-row cosine similarity "
      f"{rfs.set_index('population').loc['all_sample', 'median_row_cosine']:.2f}). LightGBM concentrates attribution on flags "
      f"({pct(rfg.loc['flags', 'lgbm_share'], 0)}); the forest spreads it over packet-size features "
      f"({pct(rfg.loc['fwd_size', 'rf_share'] + rfg.loc['pkt_size_both', 'rf_share'] + rfg.loc['bwd_size', 'rf_share'], 0)} for "
      "forward, both-direction and backward sizes) and gives flags "
      f"{pct(rfg.loc['flags', 'rf_share'], 0)}. They agree on TCP window ({pct(rfg.loc['tcp_window', 'lgbm_share'], 0)} vs "
      f"{pct(rfg.loc['tcp_window', 'rf_share'], 0)}) and header length. They also make largely the same errors: "
      f"{F['fp_both_lgbm_rf']:,} test rows are FPs of both models (LightGBM {o['FP']:,}, RF {F['fp_rf']:,}).\n")
    w("**Interpretation:** which feature *gets the credit* depends on the model family (many features are strongly "
      "correlated, and a random forest with `max_features = sqrt` spreads credit across correlated alternatives). "
      "Feature-level SHAP rankings of the selected model should therefore not be read as properties of the data. The "
      "shared false positives indicate that both models find the reverse-direction rows attack-like. Agreement is not "
      "evidence of correctness.\n")

    w("## 15. Explanation stability\n")
    w(fig("stability_bootstrap_ranks.png", "Bootstrap rank stability"))
    w(md(st, 2))
    w(f"\n**Observed:** row-resampling stability is very high: over 200 bootstrap samples of 1,000 test rows, the top-10 set "
      f"never changed (minimum overlap {F['boot1000_top10_overlap_min']:.1f}; rank Spearman ≥ {F['boot1000_spearman_min']:.3f}); "
      f"`RST Flag Count` was ranked first in every resample. Two disjoint halves of the test set (by row parity) give top-10 "
      f"overlap {F['halves_top10_overlap']:.1f}. Across populations the ranking changes more (top-10 overlap, "
      "`m5_stability_population_top10_overlap.csv`):\n")
    w(md(ps.reset_index().rename(columns={"index": "population"}), 1))
    w("\n**Interpretation / limits:** these checks show that the *reported aggregates* are precise for this fitted model. "
      "They do not measure sensitivity to refitting (not allowed in this milestone), and §14 shows that another model "
      "family attributes differently. The dominance of `RST Flag Count` is stable for this model; its interpretation as "
      "a property of the traffic is not established.\n")

    w("## 16. Dependence and interactions\n")
    w(fig("dependence.png", "Dependence plots"))
    w(md(inter, 3))
    w(f"\n**Observed (uniform sample, 1,000 rows for interactions):** off-diagonal interaction terms account for "
      f"{pct(F['interaction_offdiag_share'], 0)} of total mean |interaction| mass, and the strongest pairs all involve "
      "`RST Flag Count` (with `Flow Duration`, `Bwd PSH Flags`, `Bwd Packet Length Std`, `Bwd Init Win Bytes`). "
      f"Rows with `RST Flag Count` ≥ 1 receive {dep['rst_ge1_shap_q05_q95'][0]:+.1f} to {dep['rst_ge1_shap_q05_q95'][1]:+.1f} log-odds from it "
      f"(5–95 %), rows with 0 receive {dep['rst_0_shap_q05_q95'][0]:+.1f} to {dep['rst_0_shap_q05_q95'][1]:+.1f}. Median `Flow Duration` SHAP is "
      f"{dep['duration_lt100us_shap_median']:+.2f} for flows shorter than 100 µs vs {dep['duration_ge100us_shap_median']:+.2f} otherwise. "
      f"The {dep['bwd_win_shap_gt1_rows']} sampled rows where `Bwd Init Win Bytes` adds more than +1 log-odds have window values "
      f"{dep['bwd_win_shap_gt1_value_q05_q95'][0]:.0f}–{dep['bwd_win_shap_gt1_value_q05_q95'][1]:.0f} (5–95 %) — a narrow band. "
      "The TCP-window and header-length fields flagged in Milestone 2 have modest global shares "
      f"(TCP window {pct(gp.loc['all_test', 'tcp_window'], 1)}, header length {pct(gp.loc['all_test', 'header_length'], 1)}), "
      "and `Bwd Header Length` (including its negative, probably overflowed values) has small SHAP values.\n")
    w("**Interpretation:** single-feature dependence plots are incomplete descriptions of this model because about half "
      "of the attribution arises from interactions centred on the reset count. The narrow `Bwd Init Win Bytes` band is a "
      "plausible victim-OS/server signature (hypothesis, consistent with Milestone 2).\n")

    w("## 17. Interpretation of the validation→test FPR shift\n")
    w(fig("fpr_by_direction_val_test.png", "FPR by direction"))
    d2 = dec.copy()
    d2["fpr (95 % CI)"] = d2.apply(lambda r: ci_txt(r, 3) if r.benign else "undefined", axis=1)
    w(md(d2[["partition", "daygroup", "reverse_of_attack", "benign", "fp", "fpr (95 % CI)"]]) + "\n")
    w("Time windows (dataset timestamps) of the BENIGN stratum's chronological partitions vs the Thursday/Friday attack "
      "scenarios, with the number of reverse-direction benign rows in each partition:\n")
    w(md(T("shift_time_windows").fillna("")) + "\n")
    w(fig("benign_score_tails_val_test.png", "Benign score tails"))
    w("Benign score quantiles by direction and day group (`share_ge_threshold` = FPR):\n")
    w(md(sq, 4))
    kmax = ks.groupby("rows").ks.max()
    tbr = F["train_benign_reverse_share"]
    w("\nEvidence, ranked by strength:\n")
    w(f"**Directly observed**\n"
      f"1. Excluding reverse-direction rows, benign FPR is {ci_txt(tr_other)} on test vs {ci_txt(va_other)} on validation — the "
      "0.1 % target approximately holds for that traffic.\n"
      f"2. Reverse-direction benign rows are {pct(tr_all.benign / ben_test, 2)} of test benign rows vs "
      f"{pct(va_rev.benign / ben_val, 2)} of validation benign rows, and in training almost none on Thursday/Friday "
      f"(share {tbr['thursday']:.1e} Thursday, {tbr['friday']:.1e} Friday, {tbr['mon-wed']:.1e} Monday–Wednesday). "
      f"On test they account for {int(tr_all.fp):,} of {o['FP']:,} FPs.\n"
      f"3. Where such rows occur on validation Thursday they are flagged too ({int(D('val', 'thursday', True).fp)} of "
      f"{int(D('val', 'thursday', True).benign)}); validation simply contains very few of them.\n"
      f"   Reverse direction alone is not what the model flags: replies to Monday–Wednesday attack pairs are not flagged "
      f"({int(D('val', 'mon-wed', True).fp)}/{int(D('val', 'mon-wed', True).benign)} validation, "
      f"{int(D('test', 'mon-wed', True).fp)}/{int(D('test', 'mon-wed', True).benign)} test).\n"
      f"4. Their scores sit far above the threshold (Thursday test reverse median {sq[(sq.partition == 'test') & (sq.group == 'reverse|thursday')]['q0.5'].iloc[0]:.3f}), "
      "so the gap is not a matter of threshold fragility near the decision boundary.\n"
      f"5. Validation FPs ({F['val_fp_n']}) are explained by nearly the same features as test FPs (top-10 overlap "
      f"{F['val_vs_test_fp_top10_overlap']:.1f}, Spearman {F['val_vs_test_fp_spearman']:.2f}; {pct(F['val_fp_reverse_share'], 0)} of them reverse-direction).\n")
    w(f"**Strongly supported**\n"
      f"6. The shift is compositional (host-pair/scenario shift), not a general drift of benign traffic: for the eight "
      f"features that carry test FPs, the KS distance between validation and test benign distributions is at most "
      f"{kmax.max():.3f} per day group (`m5_feature_shift_val_test.csv`). The per-stratum chronological cut puts the "
      "BENIGN validation window at the start of the Thursday/Friday afternoon scan scenarios and the test window over the "
      "rest of them (time-window table above), and most reply-direction rows fall in the test window.\n"
      "7. The model scores these rows like scan flows (§9: SHAP profile closest to Portscan; `RST Flag Count`, µs-scale "
      "duration).\n"
      "8. Training exposure matters: under the random split, where such rows also occur in training, the same model "
      f"configuration flags {pct(F['E2_fpr_reverse'], 1)} of them (§13). This is an observational comparison of two frozen "
      "models, not a controlled experiment.\n")
    w("**Plausible**\n"
      "9. The rows are flow-meter fragments of scan/DDoS exchanges initiated by the victim side, labelled BENIGN by "
      "source-matching rules (labelling asymmetry / scenario artefact).\n"
      f"10. The smaller Monday–Wednesday increase (non-reverse FPR {ci_txt(D('test', 'mon-wed', False), 3)} vs "
      f"{ci_txt(D('val', 'mon-wed', False), 3)}) is mostly Wednesday `- Attempted` rows of the Slowhttptest scenario, i.e. "
      "a consequence of the Attempted → benign target policy.\n")
    w("**Unresolved**\n"
      "11. Why only about half of Friday reverse rows are flagged while Thursday's almost all are.\n"
      "12. Whether these rows should be considered attack traffic — a labelling question outside protocol v1 (a protocol-v2 "
      "sensitivity analysis could test it without replacing v1 results).\n"
      "13. Whether the conclusions hold for other fits of the same model (not testable without retraining).\n")

    w("## 18. Rare attack classes (case-level only)\n")
    rc = rare.groupby(["label", "n_label"]).agg(detected=("outcome", lambda s: int((s == "TP").sum()))).reset_index()
    w(md(rc))
    w("\n**The data are insufficient for stable family-level SHAP estimates for these labels.** Individual rows (score, "
      "outcome, top contributions) are listed in `reports/generated/m5_rare_family_cases.csv`; Heartbleed, SQL Injection "
      "and XSS rows:\n")
    rr = rare[rare.label.isin(["Heartbleed", "Web Attack - SQL Injection", "Web Attack - XSS"])]
    w(md(rr[["label", "source_row", "novel", "score", "outcome", "top_toward_attack", "top_toward_benign"]], 4))
    w("\n**Observed (exploratory):** the detected web-attack rows are carried mostly by `Fwd PSH Flags`, `Bwd Init Win Bytes` "
      "and forward sizes. Nothing here generalises beyond these rows.\n")

    w("## 19. Local explanation casebook\n")
    w("Cases are chosen by a fixed rule from the stratified sample (median-score row of each candidate set, ties by row ID); "
      "RF columns show the frozen forest's top contributions (probability units) for the same row.\n")
    for _, r in cb.iterrows():
        w(f"**{r.case}** — `{r.source_file}:{r.source_row}` ({r.day}), label `{r.label_original}` (y = {r.y_binary}), "
          f"score {r.score:.4f} vs threshold {r.threshold:.4f} → prediction {r.prediction}; novel = {r.novel}; protocol "
          f"{r.protocol}; `{r.src_dst}`; reverse-of-attack pair = {r.reverse_of_attack_pair}.  \n"
          f"LightGBM toward attack: {r.lgbm_top_toward_attack or '—'}  \n"
          f"LightGBM toward benign: {r.lgbm_top_toward_benign or '—'}  \n"
          f"RF toward attack: {r.rf_top_toward_attack if isinstance(r.rf_top_toward_attack, str) else '—'}  \n"
          f"RF toward benign: {r.rf_top_toward_benign if isinstance(r.rf_top_toward_benign, str) else '—'}\n")

    w("## 20. Score-distribution analysis (no recalibration)\n")
    w(md(sqo, 5))
    w("\n**Observed:** benign score quantiles up to the 90th percentile agree across day groups and partitions; the difference is a block "
      "of Thursday/Friday test rows at a handful of high scores (the plateaus in the tail figure, §17). No calibration model "
      "was fitted and the threshold was not changed.\n")

    w("## 21. Limitations\n")
    w("- SHAP explains the model, not the network: attributions are not causal, and correlated features share credit in "
      "model-dependent ways (§14).\n"
      "- Path-dependent TreeSHAP attributes using the training distribution's tree cover; interventional SHAP with a "
      "background set could give different splits of credit among correlated features.\n"
      "- One fitted model per family; no refit variability (retraining was out of scope).\n"
      "- The reverse-direction flag uses metadata and the benchmark's own labels; it is a descriptive grouping, not a "
      "label correction.\n"
      "- Small classes (Heartbleed 3, SQL Injection 4, XSS 5, Infiltration 11, Brute Force 22 test rows) support case "
      "descriptions only.\n"
      "- All findings are about the 2017 testbed and within-scenario evaluation; nothing here indicates real-world behaviour.\n")

    w("## 22. Reproducibility\n")
    w("```bash\n.venv/bin/python scripts/m5_explain.py              # SHAP census + samples -> artifacts/m5 (~14 min)\n"
      ".venv/bin/python scripts/m5_analyze.py              # tables, facts, figures\n"
      ".venv/bin/python scripts/m5_explain.py --out DIR    # independent rerun\n"
      ".venv/bin/python scripts/m5_explain.py --verify DIR # compare + hash outputs -> m5_reproducibility.json\n"
      ".venv/bin/python scripts/render_m5.py\n```\n")
    w(md(pd.DataFrame([
        ("Python / shap / LightGBM / scikit-learn / numpy / pandas / matplotlib",
         f"{P['python']} / {P['shap']} / {P['lightgbm']} / {P['sklearn']} / {P['numpy']} / {P['pandas']} / {P['matplotlib']}"),
        ("Sampling seed", str(RUN["seed"])), ("Code version at compute time", f"`{P['git_commit']}` (uncommitted tracked changes present: {P['git_tracked_changes']} — the Milestone 5 code was not yet committed)"),
        ("Compute time (s)", ", ".join(f"{k} {v}" for k, v in F["timing_s"].items())),
    ], columns=["Item", "Value"])))
    if REP:
        eq = REP["artifact_contents_equal"]
        w(f"\n**Verified:** an independent rerun of the compute stage produced identical contents for "
          f"{sum(eq.values())} of {len(eq)} artifact tables (SHAP matrices, sample row IDs, interactions); run metadata equal "
          f"apart from timestamps/timings: {REP['run_json_equal_except_time']}. Generated tables, facts and figures "
          f"byte-identical across two analysis runs: {REP['outputs_identical_to_previous_verify']} "
          f"({len(REP['output_sha256'])} files; SHA-256 list in `m5_reproducibility.json`). Figures are written without "
          "software-version metadata; byte identity is claimed only as verified here, on this machine and library set.\n")
    (ROOT / "reports" / "EXPLAINABILITY_ANALYSIS.md").write_text("\n".join(out))
    model_card(F, P, o, g, gp, tr_all, tr_other, rfs, sel)


def model_card(F, P, o, g, gp, tr_all, tr_other, rfs, sel):
    S = pd.read_csv(GENERATED / "m4_test_summary.csv")
    r = S[(S.experiment == "E1_primary__lgbm") & (S.subset == "full_test") & (S.budget == 0.001)].iloc[0]
    v = json.loads((ROOT / "configs/m4_frozen.json").read_text())
    e = next(x for x in v["experiments"] if x["run_id"] == v["overall_selected"])
    out = []
    w = out.append
    w("# Model Card — CIC-IDS2017 binary intrusion detector (protocol v1)\n")
    w("Generated by `scripts/render_m5.py`; performance figures are quoted from the Milestone 4 tables "
      "(`reports/MODEL_EVALUATION.md`), explanation figures from Milestone 5 (`reports/EXPLAINABILITY_ANALYSIS.md`). "
      "Research/portfolio artefact; **not a production IDS**.\n")
    w("## Model\n")
    w(f"- Selected model: `{e['run_id']}` — LightGBM binary classifier, parameters `{json.dumps(e['params'])}`, "
      f"{e['best_iteration']} trees (validation early stopping). File `{e['model_path']}`, SHA-256 `{e['model_sha256']}`.\n"
      f"- Inputs: {F['n_model_inputs']} CICFlowMeter-improved flow statistics (`configs/feature_manifest_v1.json`, default set; "
      "no IPs, ports, timestamps or identifiers).\n"
      f"- Output: probability of attack; alert when score ≥ {e['thresholds']['0.001']:.6f} (chosen on validation for a 0.1 % FPR target).\n"
      "- Target: 1 = successful attack; 0 = benign including `- Attempted` flows.\n")
    w("## Intended use\n")
    w("Studying detection and explanation behaviour on the CIC-IDS2017 benchmark under a leakage-aware protocol. Not for "
      "deployment, traffic monitoring or security decisions.\n")
    w("## Performance (Milestone 4, chronological test, frozen threshold)\n")
    w(f"Recall {r.recall:.5f}, precision {r.precision:.5f}, FPR {r.fpr:.5f} (validation FPR "
      f"{e['val_at_threshold']['0.001']['fpr']:.5f}), PR-AUC {r.pr_auc:.5f}; TP {int(r.tp):,}, FP {int(r.fp):,}, FN {int(r.fn):,}. "
      "Per-label recall, novel-vector results and comparison experiments: `reports/MODEL_EVALUATION.md`. The 0.1 % FPR "
      "target is not met on test.\n")
    w("## Explanations (Milestone 5)\n")
    w(f"- Method: path-dependent TreeSHAP (LightGBM native, equal to shap {P['shap']} TreeExplainer), computed for every test "
      "row. **Output space: log-odds of attack**; additivity verified on all rows.\n"
      f"- Global: `{g.feature[0]}` carries {pct(g.share_all[0], 0)} of mean |SHAP|; top five: "
      + ", ".join(f"`{f}`" for f in g.feature[:5]) + f". Groups: flags {pct(gp.loc['all_test', 'flags'], 0)}, timing "
      f"{pct(gp.loc['all_test', 'timing'], 0)}, response sizes {pct(gp.loc['all_test', 'bwd_size'], 0)}, TCP window "
      f"{pct(gp.loc['all_test', 'tcp_window'], 0)}.\n"
      f"- Several influential features (victim TCP window, response sizes) plausibly encode the lab's victim servers and "
      "tools rather than transferable attack behaviour (hypothesis).\n")
    w("## Known false-positive pattern\n")
    w(f"{int(tr_all.fp):,} of {o['FP']:,} test FPs are reply-direction flows of same-day attack host pairs (Thursday internal "
      f"scan, Friday external scan/DDoS); such flows have test FPR {pct(tr_all.fpr, 1)}, while all other benign flows have "
      f"{pct(tr_other.fpr, 3)}. They are short, reset-terminated flows that the model scores like scan traffic. They are "
      "\"false positives under the benchmark labels\"; whether they are attack traffic is a labelling question left open.\n")
    w("## Known failure cases\n")
    fn = pd.read_csv(GENERATED / "m5_fn_cases.csv")
    c = fn.groupby("label").agg(k=("label", "size"), n=("label_test_n", "first")).sort_values("k", ascending=False)
    rare = pd.read_csv(GENERATED / "m5_rare_family_cases.csv").groupby("label").n_label.first()
    w(f"{o['FN']} missed attacks ({int(fn.novel.sum())} novel vectors): " + ", ".join(f"{l} {r.k} of {r.n}" for l, r in c.iterrows())
      + f". In {int(fn.top_toward_benign.str.contains('RST Flag Count=0').sum())} of them the absent reset flag is among the top "
      f"contributions toward benign. Classes with {rare.min()}–{rare.max()} test rows have no reliable performance estimate.\n")
    w("## Uncertainty and stability\n")
    w(f"Explanation aggregates are stable under row resampling (minimum top-10 overlap {F['boot1000_top10_overlap_min']:.1f} over 200 bootstrap samples of 1,000 rows), but a "
      f"Random Forest trained on the same data attributes differently (top-10 overlap "
      f"{rfs.set_index('population').loc['all_sample', 'top10_overlap']:.1f}, rank Spearman "
      f"{rfs.set_index('population').loc['all_sample', 'spearman']:.2f}). Refit variability was not measured.\n")
    w("## Limitations\n")
    w("- Explanations describe model behaviour, **not causal network-security mechanisms**.\n"
      "- Within-scenario benchmark: train and test share tools, hosts and scripted runs; no claim of real-world or "
      "unseen-attack generalisation.\n"
      "- Validation FPR does not transfer to the test period; see the explainability report §17.\n"
      "- Protocol-v1 labels are used as given; no relabelling.\n")
    (ROOT / "MODEL_CARD.md").write_text("\n".join(out))


DG = ["mon-wed", "thursday", "friday"]

if __name__ == "__main__":
    main()
